### ISSUE TITLE
Multi Links Plus  - new option: sort links by url

### ISSUE THREAD

**Issue by Peuj** [Smile4ever/firefoxaddons#1]
Hello,

Instead of asking through the Add-on reviews, I'm asking here, it's easier. :)

So my request is to have an option to sort the selected links by URL before to open them.

The way Multi Links Plus grabs the links is logical but not always convenient.
For example on this website http://www.kidjutsu.com/title/inverloch, I want to open all the links related with the comic.
Depending on how I will select the links, the order of the opened links will not be the same.
So if I want to open all the links for each volume of the comics but keep the order as it's displayed then I can only select line by line.

With the sort by URL option I can select all the links and let Multi Links Plus sorts the links before opening them.

As this may not be common use-case, depending of the needs, it could be nice to activate the option with a key like the letter "s".

I hope it's clear enough. :)

Thanks

**Comment by Smile4ever** [comment]
I understand what you want to say. I will try to include a rudimentary version of sorting URL's before opening in a future release.

**Comment by Smile4ever** [comment]
As bugfixing gets boring and frustrating, I will soon be looking at introducing sorting.

Simple sorting would cause these kind of "problems":
http://test.com/manual/1
http://test.com/manual/2
...
**http://test.com/manual/10
http://test.com/manual/100
http://test.com/manual/20**
http://test.com/manual/21
http://test.com/manual/22
...

The page below could contain the solution to avoid that.
http://stackoverflow.com/questions/4340227/sort-mixed-alpha-numeric-array

I will try to include this in the long left click menu as well as a permanent option that can be enabled/disabled from the Options.

**Comment by Smile4ever** [comment]
https://github.com/Smile4ever/firefoxaddons/commit/3137a640eedeb1d4239d3cf3404d45609dacb854 implements this feature request. The sorting is now available in Multi Links Plus 3.9.0, which can be downloaded at https://addons.mozilla.org/nl/firefox/addon/multi-links-plus/versions/3.9.0.

Please let me know what you think of this new feature. I will close this issue, but you can still comment :)
