### ISSUE TITLE
fastnav feature: allow /page34 (ex: XDA)

### ISSUE THREAD

**Issue by OhSoGood** [Smile4ever/firefoxaddons#101]
Hi,

Thanks for this extension! Could you add the scheme /pageXX where XX is a number? It is commonly used, like in XDA forum.

Regards

**Comment by Smile4ever** [comment]
Sure!

**Comment by OhSoGood** [comment]
Wonderful.
I'm also using a the Redirector extension ( https://addons.mozilla.org/fr/firefox/addon/redirector/ ) which, intrinsically, is very close to this one - both manipulates the URLs to allow better privacy. Yet, having two extensions looks unoptimised, and mainly I'm afraid of potential conflict.

What's your opinion on it?

**Comment by OhSoGood** [comment]
Wonderful.

**Comment by Smile4ever** [comment]
Please keep the issue open to track the implementation of /pageXX

**Comment by Smile4ever** [comment]
https://github.com/Smile4ever/firefoxaddons/commit/99a6aa925759866694bcab5c73bb22bbc08b152a is available in FastNav 1.2.0 which has been published to addons.mozilla.org. This allows /page34 functionality.
