### ISSUE TITLE
Neat URL: add Aliexpress tracking parameter

### ISSUE THREAD

**Issue by dartraiden** [Smile4ever/firefoxaddons#103]
_spm_ (example: [click on any item from the store](https://aliexpress.com/store/all-wholesale-products/2185029.html))

In addition, it would be a good idea to add

aff_platform
cpt
sk
aff_trace_key
terminal_id

This tags added by partner sites that receive % of the purchase made by the link.

**Comment by Smile4ever** [comment]
I could add these:

spm@aliexpress.com
aff_platform
aff_trace_key
terminal_id

I'm quite sure sk and cpt are used for different purposes as well and adding them might break other sites. But feel free to add them yourself to the preferences.

**Comment by dartraiden** [comment]
> spm@aliexpress.com

Will this work with ru.aliexpress.com, de.aliexpress.com, etc?

**Comment by Smile4ever** [comment]
Good catch.

We need these:
spm@*.aliexpress.com
scm@*.aliexpress.com
aff_platform
aff_trace_key
terminal_id

**Comment by Smile4ever** [comment]
Added in 4.1.1.

**Comment by crssi** [comment]
Hmmm... just one question:

Does spm@*.aliexpress.com covers also domain aliexpress.com or only subdomain.aliexpress.com?

Should we have two rules for specofic parameter to cover them all like:
spm@*.aliexpress.com
spm@aliexpress.com

**Comment by Smile4ever** [comment]
> Does spm@*.aliexpress.com covers also domain aliexpress.com or only somesubdomain.aliexpress.com?

It covers both. According to my tests, the *.aliexpress.com parameters work as intended: strip the parameter from the root domain and the subdomains.

Given the rule `test@*.hugsmile.eu` http://hugsmile.eu/nl/?test is rewritten to http://hugsmile.eu/nl

> Should we have two rules for specofic parameter to cover them all like

No, if that is needed that would be a bug.
