### ISSUE TITLE
Multi Links Plus is Not Working on My Firefox v50.0

### ISSUE THREAD

**Issue by GaneshKandu** [Smile4ever/firefoxaddons#11]
Multi Links Plus v3.9.1 is Not Working on My Firefox v50.0 Build Id 20161104212021 ( Windows7 64 bit )

When i am selecting anchors it friezes my Browser

![untitled](https://cloud.githubusercontent.com/assets/12833130/20477866/bd4bf7c8-affd-11e6-9789-50129adb6585.png)

**Comment by Smile4ever** [comment]
Hi. Thanks for the screenshot.

I would like some more information:

1) Is this on every page?
2) Do you have multiprocess Firefox enabled or disabled?

**Comment by GaneshKandu** [comment]
yes it's on every page

multiprocess Firefox is disabled
![mpf](https://cloud.githubusercontent.com/assets/12833130/20510558/38c0b3fa-b097-11e6-87a6-496132c75427.png)

**Comment by Smile4ever** [comment]
What computer hardware do you use?
* CPU speed / number of cores
* HDD or SSD?

What software do you use?
* Operating system and version
* Firefox version

**Comment by GaneshKandu** [comment]
I have Reinstalled My Browser Now its working Fine Thanks a Lot !
