### ISSUE TITLE
[Neat URL] Make it possible to add exceptions

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#111]
Hi @Smile4ever 

Is there a way to make an exception?

For example I would like to generaly clean `blahblah` parameter, but not for somedomain.com.

Thank you and cheers

**Comment by Smile4ever** [comment]
Not yet.

**Comment by Smile4ever** [comment]
Added in 4.1.0.

Adding exceptions is the same as adding rules, but they are preceded by a exclamation mark:
!ref@google.be means do not clean "ref" at "google.be".

**Comment by crssi** [comment]
Thank you. :smile:
