### ISSUE TITLE
[Neat URL] Sharing my config for whom it might concern

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#112]
**Blocked parameters:**
`$/ref@amazon.*, _encoding, _hsenc, _hsmi, _openstat, 77campaign, action_object_*, action_ref_*, action_type_*, ad_*, adset_*, aff_platform, aff_trace_key, algo_*, aqs, bav, bih, biw, btsid, bvm, CAMPAIGN, campaign_*, cn, cp, csi, cvid, d@banggood.com, dni, dpr, dq, e@linkedin.com, ei@google.*, ek, elq*, ems_l, fb_*, feature, feeditemid, form, forward, fromEmail, ga_*, gclid, goalType, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd, hmb_*, iact, icid, ijn, Itemid, kw, lkid@gearbest.com, li@linkedin.com, lipi, loc_, mailid, mc_*, midToken, mkt_*, nb, ncid, ndsp, nid, nr_email_referer, oq, ORIGIN, p@banggood.com, pbx, pd_rd_*, pf_rd_*, pk_campaign, pk_kwd, pq, prmd, psc, qp, ref_, refsrc, rni, RSS*, sc, sc_*, sclient, scm@*.aliexpress.com, scroll, sei, sk, sp, spm@*.aliexpress.com, sr, sr_share, stick, subid, tbnid, tctx, terminal_id, trackId, trk, trkEmail, tt_*, ut, utm_*, ved, vero_*, vet, wid@gearbest.com, wmode, ws_ab_*, yclid, yv`

**URL request types:**
` font, image, imageset, main_frame, media, object, object_subrequest, script, stylesheet, sub_frame, websocket, xbl, xml_dtd, xmlhttprequest, xslt, other`
see: [https://github.com/Smile4ever/firefoxaddons/issues/112#issuecomment-357528671](https://github.com/Smile4ever/firefoxaddons/issues/112#issuecomment-357528671)

@Anyone Any comments, additions or substractions?

EDIT: Thanks to @Tallefer I have updated the Blocked parameters and removed "duplicates".
Updated: 31.3.2018

**Comment by crssi** [comment]
Addition to the upper Blocked parameters in the test phase:
`trk, midToken, fromEmail, ut, feeditemid, loc_, ad_*, adset_*, campaign_*`

Removed `beacon, ping` from upper since I am having those blocked generally over FF preferences by:
``` js
user_pref("browser.send_pings", false);
user_pref("browser.send_pings.require_same_host", true);
user_pref("beacon.enabled", false);
```

**Comment by Tallefer** [comment]
Why there are so many doubles/supersets? And they are literally next to each other.

**Comment by crssi** [comment]
Which doubles?

**Comment by Tallefer** [comment]
Well... To save time, I'll sort them out myself then. :)

$/ref@amazon.*, _encoding@amazon.*, _hsenc, _hsmi, _openstat, 77campaign, action_object_*, action_ref_*, action_type_*, adset_*, ad_*, aff_platform, aff_trace_key, algo_*, aqs, bav, bih, biw, btsid, bvm, CAMPAIGN, campaign_*, cn, cp, csi, cvid@bing.*, dpr, dq, ei@google.*, elq*, ems_l, fb_*, feature@youtube.*, feeditemid, form@bing.*, forward, fromEmail, ga_*, gclid@youtube.*, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd@google.*, hmb_*, iact, icid, ijn, Itemid, kw@youtube.*, loc_, mailid, mc_*, midToken, mkt_*, nb@tweakers.*, ncid, ncid@techcrunch.*, ndsp, nid, nr_email_referer, oq, ORIGIN, pbx, pf_rd_*, pk_campaign@vivaldi.*, pk_kwd@vivaldi.*, pq, prmd, psc@amazon.*, qp@bing.*, qs@bing.*, refsrc, ref_, sa, sc@bing.*, sclient, scm@aliexpress.*, scroll, sc_*, sei@google.*, sk@bing.*, sp@bing.*, spm@aliexpress.*, sr@techcrunch.*, sr_share, sr_share@techcrunch.*, stick, subid, tbnid, tctx@netflix.*, terminal_id, trackId@netflix.*, trk, tt_content@twitch.*, tt_medium@twitch.*, u@tweakers.*, ut, utm_*, ved, ved@google.*, vero_*, vet, ws_ab_*, yclid, yv

But supersets are still there, so you should decide what to do with them:
ncid, ncid@techcrunch.*
sr_share, sr_share@techcrunch.* (potentially also sr@techcrunch.* )
ved, ved@google.*
Well... To save time, I'll sort them out myself then. :)

$/ref@amazon.*, _encoding@amazon.*, _hsenc, _hsmi, _openstat, 77campaign, action_object_*, action_ref_*, action_type_*, adset_*, ad_*, aff_platform, aff_trace_key, algo_*, aqs, bav, bih, biw, btsid, bvm, CAMPAIGN, campaign_*, cn, cp, csi, cvid@bing.*, dpr, dq, ei@google.*, elq*, ems_l, fb_*, feature@youtube.*, feeditemid, form@bing.*, forward, fromEmail, ga_*, gclid@youtube.*, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd@google.*, hmb_*, iact, icid, ijn, Itemid, kw@youtube.*, loc_, mailid, mc_*, midToken, mkt_*, nb@tweakers.*, ncid, ncid@techcrunch.*, ndsp, nid, nr_email_referer, oq, ORIGIN, pbx, pf_rd_*, pk_campaign@vivaldi.*, pk_kwd@vivaldi.*, pq, prmd, psc@amazon.*, qp@bing.*, qs@bing.*, refsrc, ref_, sa, sc@bing.*, sclient, scm@aliexpress.*, scroll, sc_*, sei@google.*, sk@bing.*, sp@bing.*, spm@aliexpress.*, sr@techcrunch.*, sr_share, sr_share@techcrunch.*, stick, subid, tbnid, tctx@netflix.*, terminal_id, trackId@netflix.*, trk, tt_content@twitch.*, tt_medium@twitch.*, u@tweakers.*, ut, utm_*, ved, ved@google.*, vero_*, vet, ws_ab_*, yclid, yv

But supersets are still there, so you should decide what to do with them:
ncid, ncid@techcrunch.*
sr_share, sr_share@techcrunch.* (potentially also sr@techcrunch.* )
ved, ved@google.*

**Comment by crssi** [comment]
Oh, I see now what you mean. Nice catch.
About sorting. Obviously I have sorted them case-sensitive, not being aware and non-intentional. ;)
Those doubles are also non-sense and should be thrown out.

Thank you

**Comment by crssi** [comment]
I have updated first post by @Tallefer suggestions.

@Smile4ever, do you might remember why the following are tight to specific domain?
Was there any known breakage on some other domain? Asking just, since I haven't found any breakage.
```
ncid@techcrunch.*
sr_share@techcrunch.*
ved@google.*
```

Same question goes for `sr@techcrunch.*`, which I haven't generalized yet.

**Comment by Tallefer** [comment]
I have no idea how those settings are stored internally, but sorting them alphabetically on input (case-sensitive or not) makes sense, because of this possible problem with occasional doubles. :) 
Any performance-targeted sorting should be done by the plugin itself, imo.

**Comment by Smile4ever** [comment]
@crssi Only the ved@google.* parameter is included by default. I merely assign them to a domain to prevent conflicts, and since I haven't encountered them on other domains yet I have not made them general.

**Comment by crssi** [comment]
@Smile4ever thank you.
Will leave here as is and generalize all in my working profile to see in the next month for any breakage.
Cheers

**Comment by crssi** [comment]
Latest I have and testing now for a week and had no breakage until now
`$/ref@amazon.*, _encoding, _hsenc, _hsmi, _openstat, 77campaign, action_object_*, action_ref_*, action_type_*, adset_*, ad_*, aff_platform, aff_trace_key, algo_*, aqs, bav, bih, biw, btsid, bvm, CAMPAIGN, campaign_*, cn, cp, csi, cvid, dpr, dq, ei@google.*, elq*, ems_l, enablejsapi, fb_*, feature, feeditemid, form, forward, fromEmail, ga_*, gclid, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd, hmb_*, iact, icid, ijn, Itemid, kw, loc_, mailid, mc_*, midToken, mkt_*, nb, ncid, ndsp, nid, nr_email_referer, oq, ORIGIN, origin, pbx, pf_rd_*, pk_campaign, pk_kwd, pq, prmd, psc, qp, qs, refsrc, ref_, sa, RSS*, sc, sclient, scm, scroll, sc_*, sei, sk, sp, spm, sr, sr_share, stick, subid, tbnid, tctx, terminal_id, trackId, trk, tt_*, ut, utm_*, ved, vero_*, vet, ws_ab_*, wmode, yclid, yv`

**Comment by OhSoGood** [comment]
crssi: Thank you. Please keep updating and sharing!

**Comment by crssi** [comment]
Thank you... plan to update in a week or two.
I haven't done any measurements, since I didn't feel any noticed slowdowns, but I would be happy to hear your observations.

To measure use [Gecko Profiler](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler) and make two tests... first with only one "Blocked parameter" and the second with the full list.

Cheers

**Comment by OhSoGood** [comment]
Here is my list. I removed two items (can't remember which, which were hurting ecommerce websites), made spm and scm focused on aliexpress, and added two ones for gearbest.

$/ref@amazon.*, _encoding, _hsenc, _hsmi, _openstat, 77campaign, action_object_*, action_ref_*, action_type_*, adset_*, ad_*, aff_platform, aff_trace_key, algo_*, aqs, bav, bih, biw, btsid, bvm, CAMPAIGN, campaign_*, cn, cp, csi, cvid, dpr, dq, ei@google.*, elq*, ems_l, fb_*, feature, feeditemid, form, forward, fromEmail, ga_*, gclid, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd, hmb_*, iact, icid, ijn, Itemid, kw, loc_, mailid, mc_*, midToken, mkt_*, nb, ncid, ndsp, nid, nr_email_referer, oq, ORIGIN, pbx, pd_rd_*, pf_rd_*, pk_campaign, pk_kwd, pq, prmd, psc, qp, refsrc, ref_, sa, RSS*, sc, sclient, scroll, sc_*, sei, sk, sp, sr, sr_share, stick, subid, tbnid, tctx, terminal_id, trackId, trk, tt_*, ut, utm_*, ved, vero_*, vet, ws_ab_*, wmode, yclid, yv, spm@*.aliexpress.com, scm@*.aliexpress.com, wid@gearbest.com, lkid@gearbest.com

**Comment by crssi** [comment]
Compared yours and mine and did a merge with few differences.
Updated 1st post.
Replaced the aliexpress ones from yours, removed `sa` since it is problematic.

**Comment by Smile4ever** [comment]
Feel free to edit https://github.com/Smile4ever/firefoxaddons/wiki/Neat-URL---Parameter-configuration

Closing this issue, you can still comment or edit if you want.
