### ISSUE TITLE
Neat URL: Small visual issues

### ISSUE THREAD

**Issue by Tallefer** [Smile4ever/firefoxaddons#113]
Two non-critical issues:
1) Text in side menu is out of visible bounds: 
![neat1](https://user-images.githubusercontent.com/395476/35005374-3d93b914-fb04-11e7-94cb-ef32e2bc831d.png)
I'd suggest trimming the text to just "Neat URL", maybe "Neat URL enabled", but that is a bit redundant because of addon's icon state and/or tooltip text.

2) Options page having scroll bars for no obvious reason: 
![neat2](https://user-images.githubusercontent.com/395476/35005624-1481af26-fb05-11e7-95e6-f3df7cf13a44.png)
Other addons which are using similarly designed options (like Pure URL or Decentraleyes) seem quite happy with the same window width or input fields.

**Comment by Smile4ever** [comment]
Which operating system are you using? Windows XP?

**Comment by Tallefer** [comment]
Yep. Fx 56 ESR.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/113
