### ISSUE TITLE
[Neat URL] just idea - color marking

### ISSUE THREAD

**Issue by perdolka** [Smile4ever/firefoxaddons#114]
Highlight user settings by a different color.
Example:
<a href="http://piccy.info/view3/11971772/d3493e8cb6d0b1774461631144863481/" target="_blank"><img src="http://i.piccy.info/i9/957cebc77d1cfa410fde004d95cab56e/1516198662/7941/1207467/ghg_min.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2018-01-17-14-17/i9-11971772/654x257-r" target="_blank"><img src="http://i.piccy.info/a3/2018-01-17-14-17/i9-11971772/654x257-r/i.gif" alt="" border="0" /></a>

**Comment by Smile4ever** [comment]
Good idea.

**Comment by Smile4ever** [comment]
I have been working on this, but it's not that easy. I will postphone it for now. A pull request is always welcome.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/114
