### ISSUE TITLE
[Neat URL] Add some rules ,and one suggerstion

### ISSUE THREAD

**Issue by Crystal-RainSlide** [Smile4ever/firefoxaddons#116]
`source@sourceforge.net, position@sourceforge.net, callback@bilibili.com`
As there are more and more rules, can they be written in ways like:
`(source|position)@sourceforge.net` or `/source|position/@sourceforge.net`
Since Regular Expression may slow down the browser, so I'm not suggesting this. If you think it's better, just alart the users to use as less wildcard as possible~
(The latter is from uBlock Origin's Regular Expression wording in its _:has()_

So, the rules can be organized.

**Comment by Smile4ever** [comment]
I would seek other means to organise the rules better, like grouping or just sorting them alphabetically.

I believe the added complexity (both for the user and code wise) is not worth the more compact notation.

As for source@sourceforge.net, position@sourceforge.net and callback@bilibili.com - I will add those to Neat URL.
