### ISSUE TITLE
NeatUrl question

### ISSUE THREAD

**Issue by Decopi** [Smile4ever/firefoxaddons#117]
Hi Geoffrey! Please, a simple question:

UMatrix has an option called "Block all hyperlink auditing attempts". It is explaining in the following text:

"Hyperlink auditing is a mechanism which allow a party, any party, to be informed about which link a user clicked on a particular web page. It is essentially a tracking feature: it allows a web site, or any third-party to that web site, to be informed about which link you clicked on which one of its web pages. The sole purpose is to track your browsing activity."

Geoffrey, my simple question is if this UMatrix option has the same function as NeatUrl?

Thank you in advance!

**Comment by Smile4ever** [comment]
Neat URL cleans query parameters from URLs just before you visit them.
UMatrix does the same in another way. It might not have the same features though. I have no experience with UMatrix.
