### ISSUE TITLE
About ?ref=

### ISSUE THREAD

**Issue by WildCrow** [Smile4ever/firefoxaddons#118]
Is there a particular reason why this is not enabled by default ? I just added in my blocked parameters **ref** and sometimes works and sometimes doesn't, for example on links from webdesignernews.com, it's kinda random. Thanks in advance.

**Comment by DReaper** [comment]
I'm having the exact same issue with ?ref_. For some reason, it will remove the ?ref tag on Amazon.com but not on Amazon.ca.

**Comment by Smile4ever** [comment]
@WildCrow Do you have example URLs?
@DReaper Do you have example URLs?

**Comment by WildCrow** [comment]
https://www.webdesignernews.com/  

Every link from there adds "?ref=webdesignernews.com", some links are cleaned others don't, not sure why.

**Comment by Smile4ever** [comment]
> Is there a particular reason why this is not enabled by default ? I just added in my blocked parameters ref and sometimes works and sometimes doesn't, for example on links from webdesignernews.com, it's kinda random. Thanks in advance.

I will enable it by default in the next release. I have not been able to reproduce your issue with the URL not being cleaned on webdesignernews.com.

> I'm having the exact same issue with ?ref_. For some reason, it will remove the ?ref tag on Amazon.com but not on Amazon.ca.

I believe this is not the same issue. Try to use $$/ref@amazon.* (at your own risk, it might break pages on Amazon!). If you want less risk, please see which parameters are in the URL which need to be cleaned. Only if there are no "normal" parameters left, it will clean everything after /ref. $/ref means "ends with /ref", an additional $ means force even when there are still other parameters (for example, if a parameter pd_rw is still present in the URL you try to clean, add that to Neat URL and try again).

**Comment by Smile4ever** [comment]
For #130 I've removed the parameter by default in version 4.1.2. After updating to 4.1.2 you can add "ref" back to your list of parameters if you want.
