### ISSUE TITLE
Multi links plus 3.9.2 Context menu issue

### ISSUE THREAD

**Issue by rayman89** [Smile4ever/firefoxaddons#12]
The new version makes it so when you right click on a tab the lasso appears along with it's menu.

**Comment by Smile4ever** [comment]
Hi thanks for reporting this. This is indeed a bug and will be fixed as soon as possible. I will keep you informed.

**Comment by Smile4ever** [comment]
Fixed with https://github.com/Smile4ever/firefoxaddons/commit/8cf7b2f1cfe8d58bfd306d5f56fff517e21188d7 available in Multi Links Plus 3.9.3.

**Comment by rayman89** [comment]
Thanks a lot for fixing it so quickly.
