### ISSUE TITLE
[Neat URL] Additional Amazon rules 

### ISSUE THREAD

**Issue by stordoff** [Smile4ever/firefoxaddons#120]
Using the default ruleset, Amazon (UK) links continue to contain a bunch of seemingly useless parameters.

https://www.amazon.co.uk/My-Neighbour-Totoro-Blu-ray-DVD/dp/B008LU8O7M?pd_rd_wg=fGHj7&pd_rd_r=842482ae-11b8-45dd-b87e-745f45eb3e50&pd_rd_w=Wddvp&ref_=pd_gw_qpp&pf_rd_r=Z5R5BKXV0MDMS1C09R58&pf_rd_p=c47fe71a-fa79-58c8-b164-ab38eff388c4

is only cleaned to:

https://www.amazon.co.uk/My-Neighbour-Totoro-Blu-ray-DVD/dp/B008LU8O7M?ref_=pd_gw_qpp&pf_rd_r=Z5R5BKXV0MDMS1C09R58&pf_rd_p=c47fe71a-fa79-58c8-b164-ab38eff388c4

Adding two additonal rules `ref_@amazon.*, pf_rd_*@amazon.*` appears to achieve the desired result: 

https://www.amazon.co.uk/My-Neighbour-Totoro-Blu-ray-DVD/dp/B008LU8O7M

**Comment by Smile4ever** [comment]
Added in 4.1.0.
