### ISSUE TITLE
Neat URL: Not working with Washington Post?

### ISSUE THREAD

**Issue by geeknik** [Smile4ever/firefoxaddons#121]
Am I missing something because when I visit WaPo, this is the URL I see: https://www.washingtonpost.com/news/business/wp/2018/03/02/feature/the-silicon-valley-elites-latest-status-symbol-chickens/?utm_term=.b985b78b434e

My rules:
```
$/ref@amazon.*, _encoding, _hsenc, _hsmi, _openstat, 77campaign, action_object_*, action_ref_*, action_type_*, adset_*, ad_*, aff_platform, aff_trace_key, algo_*, aqs, bav, bih, biw, btsid, bvm, CAMPAIGN, campaign_*, cn, cp, csi, cvid, dpr, dq, ei@google.*, elq*, ems_l, fb_*, feature, feeditemid, form, forward, fromEmail, ga_*, gclid, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd, hmb_*, iact, icid, ijn, Itemid, kw, loc_, mailid, mc_*, midToken, mkt_*, nb, ncid, ndsp, nid, nr_email_referer, oq, ORIGIN, pbx, pd_rd_*, pf_rd_*, pk_campaign, pk_kwd, pq, prmd, psc, qp, qs, refsrc, ref_, sa, RSS*, sc, sclient, scm, scroll, sc_*, sei, sk, sp, spm, sr, sr_share, stick, subid, tbnid, tctx, terminal_id, trackId, trk, tt_*, ut, utm_*, ved, vero_*, vet, ws_ab_*, wmode, yclid, yv
```

**Comment by crssi** [comment]
@geeknik 

Visit pure link [https://www.washingtonpost.com/news/business/wp/2018/03/02/feature/the-silicon-valley-elites-latest-status-symbol-chickens/](https://www.washingtonpost.com/news/business/wp/2018/03/02/feature/the-silicon-valley-elites-latest-status-symbol-chickens/) without `?utm_term=...` and you will see something funny will happen :smile:

I am sure that NeatURL is working just fine in this case.

Cheers

**Comment by Smile4ever** [comment]
Since the URL part is being added later, there is nothing we can do.. It will trigger a reload (probably) and we will get stuck in an infinite loop if we try to handle this scenario. WONTFIX I'm afraid.
