### ISSUE TITLE
[Neat URL] Cloud storage sync

### ISSUE THREAD

**Issue by duxet** [Smile4ever/firefoxaddons#123]
The only thing i am missing is ability to synchronize Neat URL settings in multiple devices, like it's done by uBlock Origin: https://github.com/gorhill/uBlock/wiki/Cloud-storage

**Comment by Smile4ever** [comment]
Not sure how I will implement this (whether browser.storage.local should be kept in place as well) but it's certainly something I would be willing to do.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/123
