### ISSUE TITLE
[Neat URL][REQ] port this addon/extension to Chrome?

### ISSUE THREAD

**Issue by waldens** [Smile4ever/firefoxaddons#124]
[Pure URL](https://chrome.google.com/webstore/detail/pure-url/mphlceppeighhlbggdkmcoieeckjnfjj?utm_source=chrome-app-launcher-info-dialog) is not good enough, Chrome also need Neat URL please! ☺️

**Comment by waldens** [comment]
@Smile4ever A hotheadedfriend of mine has tried to import Neat URL to chrome manually:
1. Download the file `neat-URL.xpi` and unzip it
2. Build `browser-polyfill.js` by using `https://github.com/mozilla/webextension-polyfill` and put it in the folder above
3. Modify `manifest.json`
change
```
"background": {
		"scripts": ["background.js", "toolbaricon.js"]
	},
```
To
```
"background": {
		"scripts": ["browser-polyfill.js","background.js", "toolbaricon.js"]
	},
```
4. Modify `options.html`
Add
```
 <script type="application/javascript" src="browser-polyfill.js"></script>
```
before
```
<script src="options.js" defer></script>
```

I just would like to ask b/c obviously you know your work best: Are these steps enough? <img alt="ghe-emoji" title=":_onion_head_wow2:" src="https://cloud.githubusercontent.com/assets/136959/13371851/721efa42-dcf5-11e5-8a91-ae1875cdc74c.gif">

**Comment by Smile4ever** [comment]
I think this is indeed enough, looking at the permissions (=used APIs). I will implement these changes and do some thorough tests.

**Comment by nicolaasjan** [comment]
Hi,
I would like to have this extension in Chromium as well.
Simply loading the unpacked Firefox xpi-file throws errors obviously:

```
Unrecognized manifest key 'applications'.
found unexpected key 'browser_style'
Uncaught ReferenceError: browser is not defined
Uncaught ReferenceError: browser is not defined
```

The method described above by Waldens 'hotheaded friend' is a bit to difficult for me (building browser-polyfill.js).

Are you working on a Chrome extension?

**Comment by gliptak** [comment]
Could the ```applications``` key be removed? https://github.com/Rob--W/dont-track-me-google/issues/15

**Comment by Smile4ever** [comment]
In the Chrome build, I will remove `applications` and `browser_style`. This will be retained in the Firefox build so the addon doesn't get loaded twice when using about:debugging and AMO (addons.mozilla.org) together.

Progress has been made for the Chrome build, I have it working. I will publish soon to the Chrome Web Store.

**Comment by waldens** [comment]
@Smile4ever Good job! I can't wait to enjoy it on Chrome and recommend it to the community.｡◕ ‿ ◕｡

**Comment by Smile4ever** [comment]
It has been published:
https://chrome.google.com/webstore/detail/neat-url/jchobbjgibcahbheicfocecmhocglkco

Port can be seen here: https://github.com/Smile4ever/firefoxaddons/commit/26dc2c81e7026c6b01a30028f624c0d84b54297d

Screenshot:
![image](https://user-images.githubusercontent.com/544411/40561883-210fadd2-605f-11e8-8936-69a589055eab.png)

**Comment by waldens** [comment]
@Smile4ever Thanks. Already recommend it to the community, seems very popular:
https://www.v2ex.com/t/457992

Also encountered some suspected bugs, like the rule `jd_pop@*.jd.com` seems not working for the URL `https://item.jd.com/5724596.html?jd_pop=1bb6d5c7-e6fc-41cc-99cf-08e3a9efcd4d&abt=3`
I'm not sure if this is bug or misuse yet. Anyway, big thanks~
