### ISSUE TITLE
[Neat URL] Custom parameters not working on Android

### ISSUE THREAD

**Issue by Kusresa** [Smile4ever/firefoxaddons#126]
Thanks for the great addon! I am using it on Android but I have no idea whether it is working on it (I can install it but there are no statistics or toolbar icon indicating it works). Is it able to be used on Android? Also I have tried adding a custom parameter in the setting which works well on desktop version but it doesn't take any effect on Android. Possible bug on Android version?

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/126
