### ISSUE TITLE
[Neat URL] removing "ref" breaks branch switching in GitLab

### ISSUE THREAD

**Issue by fjen** [Smile4ever/firefoxaddons#130]
Gitlab makes a requests with the `ref` parameter when switching branches in the files or commit view. Example:
https://gitlab.com/gitlab-org/gitlab-ce/refs/switch?utf8=✓&destination=tree&path=&ref=v10.1.0

Without it, you get a 404. This breaks every GitLab instance.

The issue that lead to this was #118

**Comment by Smile4ever** [comment]
Will be fixed soon.
