### ISSUE TITLE
[Neat URL] IMDb links

### ISSUE THREAD

**Issue by tzimon** [Smile4ever/firefoxaddons#131]
imdb.com uses the same parameters as amazon, which were mentioned in #120. `pf_rd*` and `ref_` should probably be applied globally.
Examples:
`https://www.imdb.com/list/ls025849840/videoplayer/vi2255206425?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=b451205e-3272-401d-add0-bce43dc9f81b&pf_rd_r=DFV026GDFMD76Q2V871Z&pf_rd_s=right-3&pf_rd_t=15021&pf_rd_i=tt0292506`

`https://www.imdb.com/movies-in-theaters/?ref_=nv_mv_inth_1`

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/131
