### ISSUE TITLE
[Neat URL] Hash parameters

### ISSUE THREAD

**Issue by tzimon** [Smile4ever/firefoxaddons#133]
spiegel.de [hompage](www.spiegel.de/) uses `#ref` instead of `?ref` on some ressort links, for example:
`http://www.spiegel.de/thema/meinung/#ref=meinunghp`
`http://www.spiegel.de/sport/#ref=ressortblock`
I can't figure out how to add a rule for them.

**Comment by Smile4ever** [comment]
Seems to be a bug, I will investigate.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/133
