### ISSUE TITLE
[Neat URL] Parameter src=search not working on addons.mozilla.org

### ISSUE THREAD

**Issue by krathalan** [Smile4ever/firefoxaddons#136]
Apologies if I'm doing this incorrectly, as I just started using the add-on.

I can't seem to get the blocked parameter "src" to work, but I've gotten others to work. Yes, I've clicked "save preferences" at the bottom.

Specifically, using the AMO search for Neat URL, `/?src=search` still shows up in the URL.

This is the link that I'm having trouble with in particular: `https://addons.mozilla.org/en-US/firefox/addon/neat-url/?src=search`

**Comment by tzimon** [comment]
I think AMO is a protected page, on which webextensions don't work. the same appears when you follow the link from the about:addons settings page:
`https://addons.mozilla.org/en-US/firefox/addon/neat-url/?src=api`

**Comment by Smile4ever** [comment]
@tzimon Neat URL handles AMO differently, so it should be supported. I will see whether the support for the alternative method broke.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/136
