### ISSUE TITLE
Impossible to get Neat URL working

### ISSUE THREAD

**Issue by mazesy** [Smile4ever/firefoxaddons#137]
_Neat URL_ (all versions, latest 4.1.3 included) / Firefox 60.0.1 (x64) / Windows 7 (x64)

It's obviously not the extension's issue since so many users run it flawlessly. But here totally impossible to get it doing its job. I have 37 extensions, no problem; I run the _ClearUrls_ extension: no issue.

Mystery. This explains my thread : hoping to get a hint on what the culprit can possibly be.
I'd prefer to switch from _ClearUrls_ to _Neat URL_ because of its ability to have my own filters added.

As it is now, _Neat URL_ gets installed, options are correctly registered by Firefox ... but on the ground: nothing works, urls when applicable are left untouched. First test is always Google and _Neat URL_'s filters (many of which apply to Google) are simply not applied, the url resulting from a quest is untouched and _Neat URL_'s badge doesn't appear of course.

Help, advice appreciated - Thanks.

**Comment by crssi** [comment]
One WE I had collided with NeatURL. Unfortunatelly I don't remember which one (obviously it was not very important one and easy to ditch).
Disable all addons except NeatURL and test again.
Enable half of them and test again.
...
...
etc., I know that you know what I mean. :)

Cheers

**Comment by mazesy** [comment]
Thanks @crssi ... yep, I know what you mean :=) i'm still trying to find the culprit in the soft way before considering as a last resort the hard way, the halves by halves way.

I'm not sure the culprit is that of an extension's incompatibility. At this time I'm checklisting Firefox settings, many of which I've tweaked. But it may be simply another extension getting on its way. That's why I started this thread with the idea any similar experience could be shared to help me on this issue.

Thanks!

**Comment by Smile4ever** [comment]
@mazesy Which addons do you have installed? Could you give me a complete list?

**Comment by mazesy** [comment]
Hi @Smile4ever , detailed .htm list available at https://mon-partage.fr/f/tucsiEDw/
Fast list as follows:

Awesome RSS
Bookmark search plus 2
Bookmarklets context menu
Clear Storage Button
ClearURLs
Close All Tabs Button
Close Tab Context Menu
ContextSearch web-ext Lite
Cookie AutoDelete
Copy page title and url
Decentraleyes
Feedbro
Foxy Gestures
Fullscreen Maps
HistoryBlock
HTTPS Everywhere
In-Site Bookmark
In-Site History
IP finder
mozlz4-edit
Page Saver WE
Redirector
Right Links WE
Scroll Up Folder
ScrollAnywhere
Search Engines Helper
SiteDelta Watch
Skip Redirect
Smart Referer
Stylus
Switch To Previous Active Tab
Tab Mix WebExtension
uBlock Origin
Viewhance
Violentmonkey
window.opener be gone

The last one, window.opener be gone, is not on AMO, installed from [here](https://github.com/earthlng/testpages/blob/master/windowopener_be_gone-1.0-an%2Bfx.xpi). That one at least is not the culprit.

Thanks. My opinion (which is why I hesitate to proceed with a systematic testing of all extensions) is that the culprit is rather in my Firefox settings. I may be wrong of course.

**Comment by crssi** [comment]
If it is the pref the I would try as first `privacy.firstparty.isolate` set to false.

**Comment by Smile4ever** [comment]
@mazesy Could you follow these steps and answer the questions marked in bold?
* Test scenario 1
1. Install Firefox Nightly
2. Install Neat URL inside a new profile
3. Enable logging in Neat URL preferences
4. Open the browser console
5. Navigate to http://www.omgubuntu.co.uk/2017/05/ubuntu-desktop-gnome-extensions-survey-1710?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+d0od+(OMG!+Ubuntu!)
6. **Attach the log from the browser console** (and make clear which log is which)

* Test scenario 2
1. Use Firefox 60
2. Use Neat URL inside a new profile (constructed as your latest comment above)
3. Enable logging in Neat URL preferences
4. Open the browser console
5. Navigate to http://www.omgubuntu.co.uk/2017/05/ubuntu-desktop-gnome-extensions-survey-1710?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+d0od+(OMG!+Ubuntu!)
6. **Attach the log from the browser console** (and make clear which log is which)

* **Also let me know what happens in test scenario 1 and test scenario 2**.
* **Do you see the Neat URL icon in your browser toolbar?**

**Comment by mazesy** [comment]
@Smile4ever many thanks for committing yourself to this issue I had opened.
Given the fact I am apparently the only user who experienced the issue (no one else here confirmed) I presume it's all in an area between the extension, the browser and maybe even my WIn7 configuration.

From there on, I have to decline your detailed testing procedures as I really don't have the time for Test (2) and that I'm really not looking forwards to installing Firefox Nightly over Firefox 60 stable. I'd have to reinstall FF60, paste back backed-up FF60 profile ... I could do it but frankly, another time maybe.

It's odd that no one but me seems to have experienced this issue. This contributes to my laziness of not carrying on -- now anyway -- your detailed tests.

Moreover I'm far from being a techie. Maybe a skilled user could devote himself but it wouldn't have any sense without my issue here described, experienced.

Thanks again :=)

**Comment by Smile4ever** [comment]
You can install Nightly alongside FF 60, it doesn't replace it.

Feel free to reopen in case you want to continue testing.

**Comment by mazesy** [comment]
> Feel free to reopen in case you want to continue testing.

Got it, thanks @Smile4ever
