### ISSUE TITLE
[Neat URL][BUG] Rule jd_pop@*.jd.com is not working.

### ISSUE THREAD

**Issue by waldens** [Smile4ever/firefoxaddons#139]
It can be reproduced both on Chrome addon and Firefox addon. (Both addons are the newest version. CentBrowser 3.4.3.39 x64 and Firefox 60.0.1 x86) Already disabled all other addons to avoid the impact of other addons.

① Remove all other rules and manually add the rule `jd_pop@*.jd.com`
② Visit `https://item.jd.com/5724596.html?jd_pop=1bb6d5c7-e6fc-41cc-99cf-08e3a9efcd4d&abt=3` to test
Expect result:
`https://item.jd.com/5724596.html?abt=3`
Actual result:
`https://item.jd.com/5724596.html?jd_pop=1bb6d5c7-e6fc-41cc-99cf-08e3a9efcd4d&abt=3`

Not sure this is bug or my misunderstanding to the rules format. Hope some kindly feedback anyway.

**Comment by Smile4ever** [comment]
This is a bug, I've found the cause. The solution will be present in the next release of Neat URL.

**Comment by Smile4ever** [comment]
This has been pushed in the form of Neat URL 4.1.5 to the Chrome Web Store and to addons.mozilla.org (AMO).
