### ISSUE TITLE
Scrollkey: improve Spanish translation

### ISSUE THREAD

**Issue by Smile4ever** [Smile4ever/firefoxaddons#14]
As reported by @rayman89, the Spanish translation of Scrollkey needs some love.

Instructions:
- Download https://raw.githubusercontent.com/Smile4ever/firefoxaddons/master/Scrollkey-webext/_locales/es/messages.json
- Open the file with Notepad++ or the like (not Notepad or Word!)
- Update the Spanish translation
- Attach the updated translation to this bug report.

Please go ahead, @rayman89 :)

**Comment by rayman89** [comment]
BTW there is something about "VIM" that I don't know what it means. Is that information the user should know about or should I take it off? 

If you have the english version of the file could you put it here for context so I can translate it more accurately to what you wanted it to say.

**Comment by Smile4ever** [comment]
Is this good? (you're looking at the in-development Scrollkey 1.1.0)
![scrollkey-preferences](https://cloud.githubusercontent.com/assets/544411/22407147/1fd3e5f6-e661-11e6-9242-c70bed24b1c8.png)

> Also I think you can make more people interested on your add-on if you make clear on the english description that the add-on allows you to specify the scroll amount. Even though I think you created the add-on focused on it making it possible to move using J/K keys I think most people would use your add-on because it gives them the ability to scroll the amount they want.

> So could be something like "Scroll pages in VIM style, using j and k shortcuts to move exactly as much as you want."

Thank you.

**Comment by rayman89** [comment]
Thats great. Couldn't be more clear.

**Comment by Smile4ever** [comment]
Available in Scrollkey 1.1.0 which was submitted to AMO for distribution just now. Diff https://github.com/Smile4ever/firefoxaddons/commit/53e660688955af5811b4986bfff6df4bc6c59243
