### ISSUE TITLE
[Neat URL] "*.L3-domain.example.com" doesn't match "L4-domain.L3-domain.example.com"

### ISSUE THREAD

**Issue by 0xbadfca11** [Smile4ever/firefoxaddons#143]
"test@*.L3-domain.example.com" dose not effect "http://L4-domain.L3-domain.example.com/foo?test".

**Comment by Taurean75** [comment]
This should also apply to the blacklist.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/143
