### ISSUE TITLE
[Neat URL] Remove XTOR ?

### ISSUE THREAD

**Issue by Draky50110** [Smile4ever/firefoxaddons#144]
Hello.

I tried an URL with XTOR and nothing removed.

Sample : https://www.nouvelobs.com/economie/20180601.OBS7572/de-canal-a-autolib-la-tres-mauvaise-passe-de-bollore.html#xtor=EPR-1-[ObsActu8h]-20180604

**Comment by Geobert** [comment]
I confirm it's broken.
Before 4.x I used `#xtor=RSS-8`, after at 4.0, I had to change to `#?xtor`. 4.1.x, none is working anymore

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/144
