### ISSUE TITLE
[Neat URL] Remove guccounter placed by UK Yahoo News

### ISSUE THREAD

**Issue by geeknik** [Smile4ever/firefoxaddons#145]
`https://uk.news.yahoo.com/wtf-former-congressman-dennis-kucinich-201950468.html?guccounter=1`

adding `guccounter@*.yahoo.com` to my preferences solved this and the page loaded without error afterward.

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/145
