### ISSUE TITLE
[Neat URL] [question] google search clean

### ISSUE THREAD

**Issue by perdolka** [Smile4ever/firefoxaddons#146]
How to add to the rules all this google search parameters, like:
biw, bih, gs_l, ei, oq etc. ?
I tried to setup rules like:
`gs_l@google.com`, `biw@*.google.com`
but it doesn't worked.

Example.

**Actual result:**
`https://www.google.com/search?tbm=isch&sa=1&ei=oCElW5eAGaeJmgXR37HADA&q=weird+stuff&oq=weird+stuff&gs_l=img.12...0.0.0.36804.0.0.0.0.0.0.0.0..0.0....0...1c..64.img..0.0.0....0.22LdBvL5qXs`

**Expected result:**
`https://www.google.com/search?tbm=isch&q=weird+stuff`

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/146
