### ISSUE TITLE
[Neat URL] - trailing « = » is not cleaned.

### ISSUE THREAD

**Issue by timovn** [Smile4ever/firefoxaddons#147]
Hi,
Removing some params leaves a trailing « = ».

Example : 
`http://www.arfy.fr/dotclear/index.php?post/2018/06/19/De-Beers-vient-d-annoncer-qu-il-allait-commercialiser-des-diamants-fabriques-en-laboratoire--ressemblant-aux-vrais-comme-deux-gouttes-d-eau-et-pour-une-fraction-de-leur-prix&utm_source=dlvit&utm_medium=gplus`

Becomes :
`http://www.arfy.fr/dotclear/index.php?post%2F2018%2F06%2F19%2FDe-Beers-vient-d-annoncer-qu-il-allait-commercialiser-des-diamants-fabriques-en-laboratoire--ressemblant-aux-vrais-comme-deux-gouttes-d-eau-et-pour-une-fraction-de-leur-prix=`

Instead of :
`http://www.arfy.fr/dotclear/index.php?post%2F2018%2F06%2F19%2FDe-Beers-vient-d-annoncer-qu-il-allait-commercialiser-des-diamants-fabriques-en-laboratoire--ressemblant-aux-vrais-comme-deux-gouttes-d-eau-et-pour-une-fraction-de-leur-prix`

(and the « / » are converted to « %2F » too).

I’m using :

- Neat URL 4.1.5
- Firefox 60.0 (on Linux)

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/147
