### ISSUE TITLE
[Neat URL] google mail - unable to use option 'move to'

### ISSUE THREAD

**Issue by bitpixl** [Smile4ever/firefoxaddons#148]
When I try to move an email from the inbox to one of my created labels (using the "move to" icon on top), I receive this error "Oops… the system encountered a problem (#76429)"

adding "mail.google.com" to the blacklist fixes this issue.

I'm using Neat URL 4.1.5 with the 'suggested blocked parameters' and 'suggested url request types' from "https://github.com/Smile4ever/firefoxaddons/wiki/Neat-URL---Parameter-configuration"

So I've been thinking about this and am wondering whats better/makes more sense, to have this issue possibly fixed by changing one of the parameters OR let my blacklist rule just stay "as is" so the current parameters keep on filtering as much as possible? I am curious which parameter is causing the issue.

Also, does "mail.google.com" restrict it to mail.google.com or does this blacklist rule impact whole google.com?

**Comment by crssi** [comment]
Wiki updated.
Try out please and close the issue, if the situation is resolved.

**Comment by bitpixl** [comment]
Works now, thanks for the quick fix!
