### ISSUE TITLE
[Neat URL] Startpage.com - Image results page blank

### ISSUE THREAD

**Issue by bitpixl** [Smile4ever/firefoxaddons#149]
When I search for images on startpage.com (using images option on top), the result page stays blank.

adding "startpage.com" to the blacklist fixes this issue.

I'm using Neat URL 4.1.5 with the 'suggested blocked parameters' and 'suggested url request types' from "https://github.com/Smile4ever/firefoxaddons/wiki/Neat-URL---Parameter-configuration"

**Comment by crssi** [comment]
Add `!sp@*.startpage.com` to parameters. Wiki page also updated now.

Thank you

**Comment by bitpixl** [comment]
Working now as intented :+1:
