### ISSUE TITLE
[Middle Click On Page Closes Tab] Allow autoscrolling

### ISSUE THREAD

**Issue by Keith94** [Smile4ever/firefoxaddons#15]
I use the autoscrolling feature a lot, maybe you can add a configurable delay when holding down middle mouse button to activate it? This could allow fast middle clicks to close tabs, and allow long middle clicks for autoscrolling.

**Comment by Smile4ever** [comment]
Working on it.

For future reference: http://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily

**Comment by Smile4ever** [comment]
Middle Click On Page Closes Tab 1.0 implements this, but it's disabled by default. See https://addons.mozilla.org/en-US/firefox/addon/middle-click-on-page-close-tab/

Version 1.0 will be available on addons.mozilla.org as soon as Mozilla approves the update.

**Comment by Keith94** [comment]
Hi!
Good work on the new version. Regarding this comment...

>The autoscrolling icon will be present as long as you don't left click or escape, but it won't do anything.

Is there any workaround to avoid this? I wish the icon would not appear until autoscrolling is started. Otherwise, when the icon is there, it eats my left click if I go to switch tabs, and looks odd in general.

**Comment by Smile4ever** [comment]
I tried to fix that, but only escape or a click initiated by the user makes the autoscrolling icon disappear.

**Comment by Smile4ever** [comment]
If I cancel the event "mousedown", the autoscrolling icon doesn't appear at all (and autoscrolling is disabled). There's no way to cancel an event after it's been executed. Also, there is no way that I know of to begin autoscrolling from within code.

If you find a way to hide the icon, you're very welcome to share your ideas or submit a pull request.

**Comment by Smile4ever** [comment]
I made some fundamental changes in 2.0 to fix some regressions introduced by 1.0, but also to introduce new features or change existing features (see https://github.com/Smile4ever/firefoxaddons/commit/3add438da11337422916d7621acd782f5441d9f5).

Version 2.0 was submitted to addons.mozilla.org and will be available soon. Please let me know if this breaks something for you.

It's possible that you will need to reinstate your settings on the options page of Middle Click On Page Closes Tab.

**Comment by Keith94** [comment]
It works well for me, no regressions that I can find yet.
