### ISSUE TITLE
[Neat URL] Google Photos - Videos stuck on loading

### ISSUE THREAD

**Issue by bitpixl** [Smile4ever/firefoxaddons#150]
When I try to play a (self recorded) video from photos.google.com, the video stays stuck on loading.
Disabling Neat URL makes the video play as intended. I tried adding "photos.google.com" (even google.com) to the domain blacklist, but that doesn't seem to work. I have no idea which rule is needed to make it work.

I'm using Neat URL 4.1.5 with the 'suggested blocked parameters' and 'suggested url request types' from "https://github.com/Smile4ever/firefoxaddons/wiki/Neat-URL---Parameter-configuration"

**Comment by crssi** [comment]
I am not using photos.google.com so I can't get to the problem.
Please enable logging in NeatURL.
Open FF browser console (ctrl+shift+j).
Go to photos.google.com to the point where video stucks.
Copy and paste here just the last `[NeatURL]` message from browser console.

**Comment by bitpixl** [comment]
Thanks for answering and pointing me in the right direction.
I'm a bit uncomfortable posting the [NeatURL] output as it seems like its the full url to my personal video.
However, I was able to figure out that it's about googlevideo.com. When I add googlevideo.com to the domain blacklist the video works.

Is there a way that I can help out without giving the (full) output?

**Comment by crssi** [comment]
Yes. In the message, there is first the original URL followed by changed URL.
Could you compare those and let me know the difference.
You can do some changes in the data parts to avoid releasing your personal ID.

**Comment by bitpixl** [comment]
So I looked at the last [Neat URL] entry in the log and here are the differences between the original and changed url:

_15&sc=yes&ratebypass_
to 
**15&ratebypass**

_ip,ipbits,expire,id,itag,source,requiressl,playlist_type,ei,susc,mm,mn,ms,mv,pl,sc,ratebypass,mime,otfp,gir,clen,lmt,dur_
to
**ip%2Cipbits%2Cexpire%2Cid%2Citag%2Csource%2Crequiressl%2Cplaylist_type%2Cei%2Csusc%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Csc%2Cratebypass%2Cmime%2Cotfp%2Cgir%2Cclen%2Clmt%2Cdur**

_pf=1&range=0-591&rn=7&rbuf=0_
to
**pf%3D1&range=0-591&rn=7&rbuf=0**

**Comment by crssi** [comment]
add `!sc@photos.google.com` to parameters

**Comment by bitpixl** [comment]
that doesn't work, but I think I should have mentioned the domain listed in the url is googlevideo.com.
I tried !sc@*.googlevideo.com and that works :+1:

**Comment by crssi** [comment]
cool, thank you

**Comment by crssi** [comment]
If you get any other findings, please, share those with us.
Thank you again and cheers
