### ISSUE TITLE
[Neat URL] Does not clean URL on Google's sites

### ISSUE THREAD

**Issue by hayohayo** [Smile4ever/firefoxaddons#151]
Neat URL does not delete query parameters from links on Google. The simplest URL that reproduces my issue is: <https://www.google.com/?utm_source=x>. `utm_source` is removed just fine on other domains.

Add-on: Neat URL 4.1.5
OS: MacOS High Sierra
Browser: Firefox 61.0

**Comment by hayohayo** [comment]
I believe, it has something to do with domain-specific blocked parameters. Once I've removed `ved@google.*, ei@google.*, sei@google.*, gws_rd@google.*, `utm_source` is properly removed.

**Comment by crssi** [comment]
It must be different on MacOS then on Windows 10, since here is working fine.
This is from browser console:
`[Neat URL]: (type main_frame): 'https://www.google.com/?utm_source=x' has been changed to 'https://www.google.com/'`

**Comment by hayohayo** [comment]
Hmm... have just tried on Debian - the same here. Works for, say, amazon.com, but not on google.com. Also, not sure how to see the logs - I don't see them in browser's console, even though I enabled them in add-on's settings.

OS: Linux, Debian 9.4
Browser: Firefox ESR 52.9.0

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/151
