### ISSUE TITLE
Translate Now - Google translation is broken

### ISSUE THREAD

**Issue by happysurf** [Smile4ever/firefoxaddons#156]
From today the Google translation on selected text is broken.
This happen on any pages.
Example: MEMORIES AND MOMENTS > in Google translate page from English to Italian I see this:

English________________________________Italian________________________________
MOMENTS%20and%20MEMORIES  |  MOMENTI% 20and% 20MEMORIES

**Comment by Smile4ever** [comment]
Ok, found. Google changed their URL structure. A fix will be released soon.

https://translate.google.com/#auto/en/From%20today%20the
=>
https://translate.google.com/#view=home&op=translate&sl=auto&tl=en&text=From%20today%20the

**Comment by happysurf** [comment]
Now is broken also the translate page feature that does't work on Firefox 66 beta.
