### ISSUE TITLE
[Neat URL] Cannot download/install addon

### ISSUE THREAD

**Issue by UrsBeeli** [Smile4ever/firefoxaddons#157]
I was trying to download and install this addon into Firefox 66.0.3 (64-bit). When clicking on the "+Add to firefox" button the site shows me a red error bar, telling me the addon could not be downloaded. If I right click on the button, I can locally store the XPI file, but when I try to drag and drop it into firefox, I am then told, it could not be installed, because it appears to be corrupt.

I've got the same issue with another addon (Smart Referer), so I am not sure if it is a general Firefox issue or just something wrong with the download of this addon...

![NeatUrlDownloadFailed](https://user-images.githubusercontent.com/4971015/57176629-5e512900-6e5a-11e9-865d-3f6b7dd72acc.jpg)

![NeatUrlCannotInstall](https://user-images.githubusercontent.com/4971015/57176631-6610cd80-6e5a-11e9-9633-20a973fe8913.png)

**Comment by Smile4ever** [comment]
Hi. This is related to Mozilla's main certificate expiring. Details here: https://www.reddit.com/r/firefox/comments/bkhtv8/heres_whats_going_on_with_your_addons_being/

**Comment by UrsBeeli** [comment]
Thanks, after some more research I stumbled across the same issue.

**Comment by Smile4ever** [comment]
A message from Mozilla:

"Due to a certificate issue, add-on approval is currently disabled. All submissions are hold in "Awaiting approval" state. For updates, please follow the [discourse thread](https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047). We apologize for the inconvenience."

**Comment by UrsBeeli** [comment]
In the meantime Mozilla seems to have rolled out a fix, all my addons work again and I managed to install Neat URL. Sorry for the noise.
