### ISSUE TITLE
Firefox 68 broke Middle Click to Close Tab

### ISSUE THREAD

**Issue by HolmesMalone** [Smile4ever/firefoxaddons#160]
Just updated to 68. After restart the middle click within the page no longer works. Middle click on the tab works properly. 

EDIT: NVM,  after a reboot normal operation resumed. Still strange, though.

**Comment by Smile4ever** [comment]
Couldn't reproduce myself. Sometimes reloading the page helps. Thanks for your report though and I'm happy it's working again for you.
