### ISSUE TITLE
Translate Now translates links even when the option is deselected, and even if not a valid URL

### ISSUE THREAD

**Issue by laniakea64** [Smile4ever/firefoxaddons#161]
**Environment**

Translate Now webext 4.0.1
Waterfox 68.0a2 or Firefox 68.0
new profile

**Steps to reproduce**

1) Translate Now Options > Advanced > Show context menu for, un-check "Link".  Save preferences.

2) go to https://chico-gordo.github.io/ , select the first line `Скриншоты всех вкладок Настроек — https://noscript.net/screenshots`

3) right-click > Translate with Google

**Expected results:** The selected text should be translated in Google Translate, as just text to translate.

**Actual results:** Translate Now treats the entire selected text as a URL link, and tells Google Translate to try to translate this bogus "URL".

**Comment by laniakea64** [comment]
Hi @Smile4ever I might be able to do a pull request fixing this, would that be helpful?

**Comment by Smile4ever** [comment]
Yes that would be wonderful.

When I was reading your bug I didn't understand but now I can see what you mean.
