### ISSUE TITLE
Translate Now: selected text does not update (2.0.0 regression)

### ISSUE THREAD

**Issue by happysurf** [Smile4ever/firefoxaddons#18]
In Translate Now 2.0.2 version the option "Reuse Tab" doesn't work.
The page remain blocked with the first translated text but if I make a refresh the page is updated correctly with the last text selection.
The previous 2.0.1 works fine.
Firefox 54 beta9 + Windows 7.
Thanks.

Suggestion: Please add your GitHub page in your extension AMO page for  bugs report.

**Comment by Smile4ever** [comment]
This bug has been resolved in Translate Now 3.0 which will soon be available on addons.mozilla.org.
