### ISSUE TITLE
FastNav WebEx: Disable in input fields

### ISSUE THREAD

**Issue by BooSN** [Smile4ever/firefoxaddons#19]
Its enabled in Input fields, i.e. Youtube Search. You can not type a "n" because your addon goes to next page.

**Comment by Smile4ever** [comment]
Fixed in version 1.0.1 which will soon be available on addons.mozilla.org. Thanks for reporting this bug.

**Comment by BooSN** [comment]
Now that was fast ;)
Thanks!

**Comment by Smile4ever** [comment]
It's now live on addons.mozilla.org.
