### ISSUE TITLE
FastNav: Preserve leading zeros

### ISSUE THREAD

**Issue by binaryDiv** [Smile4ever/firefoxaddons#20]
Currently, leading zeros are stripped from the page number, e.g. pressing 'n' on ...&p=001901 results in ...&p=1902 instead of ...&p=001902. Some websites depend on those zeros, though.

One example would be the following web comic:
http://mspaintadventures.com/?s=6&p=001901

**Comment by Smile4ever** [comment]
I added support for this in FastNav 1.0.2 which will soon be available on addons.mozilla.org.

**Comment by Smile4ever** [comment]
1.0.2 is now available to install from addons.mozilla.org.
