### ISSUE TITLE
FastNav WE goes from /10/ to /110/ instead /11/)

### ISSUE THREAD

**Issue by BooSN** [Smile4ever/firefoxaddons#21]
FastNav WE goes from /10/ to /110/ instead /11/)

**Comment by Smile4ever** [comment]
What URL did you use?

**Comment by BooSN** [comment]
Attn nsfw!

goo.gl/Mhmhwt

please delete when reviewed.

**Comment by Smile4ever** [comment]
FastNav 1.0.3 fixes this issue. It will soon be available on addons.mozilla.org.

**Comment by Smile4ever** [comment]
FastNav 1.0.3 is now available on addons.mozilla.org.
