### ISSUE TITLE
Pale Moon support?

### ISSUE THREAD

**Issue by Lootyhoof** [Smile4ever/firefoxaddons#22]
Hi,

With Firefox moving to WebExtensions, and Pale Moon not doing so (still to use XUL/Bootstrap/SDK), would you consider continuing support for the XUL versions of your add-ons? If you need a place to list them it is possible to list the compatible add-ons on the [Pale Moon Add-ons Site](https://addons.palemoon.org/), if this is of interest please let me know and I can set you up.

Thanks for the support so far and here's hoping it will continue in the future!

**Comment by Smile4ever** [comment]
Thanks for getting in touch, I have contacted you by e-mail.

**Comment by hook54321a** [comment]
@Smile4ever I'm interested in this as well.

**Comment by Smile4ever** [comment]
@hook54321a What extensions do you use in combination with Pale Moon?

**Comment by Smile4ever** [comment]
Closing since no reaction received.
