### ISSUE TITLE
Alt+F4 Closes Tab?

### ISSUE THREAD

**Issue by MatTURBO** [Smile4ever/firefoxaddons#24]
Hi,
I wanted to ask if Middle Click On Page Closes Tab would need much change to simply replace the middle click with Alt+F4?
Thx

**Comment by Smile4ever** [comment]
I will look into this. If it's possible, it won't be easy to do.

**Comment by Smile4ever** [comment]
Hi. I've looked into this and it seems like Alt+F4 is impossible. Would you be interested in F4?

**Comment by MatTURBO** [comment]
Thanks for looking into it. I'm using a mouse hotkey to close windows by Alt+F4, however, Firefox would be better if it closes a single tab instead. "Fast Close Tab" was doing just that by overriding Alt+F4 but not on Firefox Quantum anymore. Sad to hear that this seems to be impossible now.

**Comment by MatTURBO** [comment]
Oh, I finally found a solution! The mightiness of **AutoHotKey** is always surprising.

```
SetTitleMatchMode 2

#ifWinActive ahk_exe firefox.exe
!F4::Send ^w
```
