### ISSUE TITLE
[Neat URL][Feature request] intercept copy urls

### ISSUE THREAD

**Issue by CircleCode** [Smile4ever/firefoxaddons#26]
when i want to share an url, i often richt click on the link in the page, and then select _copy url_
It would be awesome if neat url was able to intercept it to clean the url. If it can not intercept this action, then an optional new contextual entry would be fine too.

**Comment by Smile4ever** [comment]
It's a good idea, Pure URL had something like this as well (but I believe this was only for stripping query parameters, correct me if I'm wrong).

Can you give me some example URLs?

**Comment by peterjanes** [comment]
[This page](http://www.bytefive.com/blogs/understanding-utm_source-utm_medium-and-utm_campaign) has a link about halfway down.

**Comment by peterjanes** [comment]
I believe Pure URL removed the URL parameters right in the DOM, rather than on an action. Don't know if that's possible, but it might be the preferred behaviour.

**Comment by atomGit** [comment]
@Smile4ever - if it helps, [Clean Links](https://github.com/diegocr/CleanLinks) has code to strip params off a copied link also, plus a number of other very useful features and options - you may want to install it and look at its preferences

unfortunately Clean Links has been removed from AMO and hasn't been worked on in years - it would be great to see some of this functionality restored in w WebExt add-on - PureURL is good, but i don;t like it as much as CL

**Comment by Tallefer** [comment]
I second this request.
Together with [Right Links](https://addons.mozilla.org/firefox/addon/right-links/) this could be an awesome combo. :)

**Comment by Smile4ever** [comment]
This is now tracked in https://github.com/Smile4ever/Neat-URL/issues/26
