### ISSUE TITLE
Scrollkey: Not working correctly on HackerNews, Trello

### ISSUE THREAD

**Issue by siboehm** [Smile4ever/firefoxaddons#29]
Scrollkey works on [HackerNews](https://news.ycombinator.com/), but always displays the annoying notification "...cannot be scrolled vertically...".

Feature Request: Add blacklisted Sites, where the extension disables itself. For example [Trello](https://trello.com/)-Boards provide shortcuts using the 'j' and 'k' keys, but Scrollkey disables those and instead displays a notification.  

PS: Love the extension, great work and exactly what I was looking for!

**Comment by Smile4ever** [comment]
Hi thanks for your bug report and feature request. The bug you mention should be fixed by db2a5df which will be available in Scrollkey 2.0.1. I will keep this issue open to track the implementation of "Add blacklisted Sites".

**Comment by Smile4ever** [comment]
This is available in Scrollkey 3.0. Thank you for your patience!
