### ISSUE TITLE
No status bar in Firefox

### ISSUE THREAD

**Issue by privacytoolsIO** [Smile4ever/firefoxaddons#3]
My Firefox Version 47.0.1 doesnt have the status bar anymore. It only works with a plugin called  Classic Theme Restorer (https://addons.mozilla.org/de/firefox/addon/classicthemerestorer/) can you show Multi Links in the regular addon bar in the head area of the browser? Thanks so much.

**Comment by privacytoolsIO** [comment]
More information: "How can I get the old Status Bar back?"
https://support.mozilla.org/en-US/kb/what-happened-status-bar#w_how-can-i-get-the-old-status-bar-back

**Comment by privacytoolsIO** [comment]
It would be nice if Multi Links would be moved to the addons bar.

**Comment by Smile4ever** [comment]
I'm working on a toolbar button, but enabling/disabling Multi Links Plus from the toolbar button doesn't work yet.

**Comment by Smile4ever** [comment]
Version 3.6.0 contains exactly what you asked for. It's available for direct installation here: https://addons.mozilla.org/en/firefox/addon/multi-links-plus/versions/3.6.0

Version 3.6.0 will reach the release channel once Mozilla approves the update. The direct installation skips the waiting time.

**Comment by privacytoolsIO** [comment]
Thank you so much.
