### ISSUE TITLE
Neat URL: Multiple errors of removing parameters from references.

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [Smile4ever/firefoxaddons#30]
When deleting parameters, you should delete parameters without values (without =), parameters in non-standard format (multiple question marks), do not spoil other parameters, do not delete the fragment without an explicit requirement.
Example of a link for test: http://example.test/path?parameter&utm_source&key=value?utm_medium=abc&parameter&utm_term?key=value&utm_medium=abc#utm_content=utm_campaign?utm_reader=utm_place&utm_reader=utm_place
Should be transformed into: http://example.test/path?parameter&key=value&parameter?key=value#utm_content=utm_campaign?utm_reader=utm_place&utm_reader=utm_place
But it turns into: http://example.test/path?parameter=undefined&key=value

**Comment by Smile4ever** [comment]
Hi. Could you provide me a valid link which demonstrates the problem?

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
This is a valid link to a special standard test domain. There is no site, but you can replace  "example.test" with "example.com". Or do you really need a link from real life from this site, which steals personal data in such a tricky way?

**Comment by Smile4ever** [comment]
Example.com will do for testing purposes, but is there actually a site which does something like this?

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
"https://www.liveinternet.ru/users/acarabanow/post381600676/" page contains a link "https://www.liveinternet.ru/journal_proc.php?action=redirect&url=http://kleopatra0707.com/partner/2065401?utm_source=partner_kleo0707_2065401" with the "http://kleopatra0707.com/partner/2065401?utm_source=partner_kleo0707_2065401" title. (This page has nothing to do with me.)

**Comment by Smile4ever** [comment]
Thanks, I will look into this.

**Comment by crssi** [comment]
Hmmm... why not keep it simple and make it stronger at what it does best and leave to Neat URL just stripping parameters?
And for redirection use "Skip Redirect" instead?
IMHO

**Comment by Smile4ever** [comment]
I agree with crssi. Please use "Skip Redirect" for this purpose.

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
"Skip Redirect" for other purposes. "Skip Redirect" handles the last example in a different way, with a different result. "Request Control" can replace your entire add-on, but it also has this error. I temporarily use "Redirector" - it solves this problem, but the regular expression is very inconvenient and big.

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
In Neat URL 3.2.0 the second question mark spoils now, by the way.

**Comment by gwarser** [comment]
@SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU  if you are brave, and have bit of coding skills (compile this yourself) you can check my pull request https://github.com/Smile4ever/firefoxaddons/pull/82
