### ISSUE TITLE
[Neat URL] Amazon links not cleaned

### ISSUE THREAD

**Issue by woctezuma** [Smile4ever/firefoxaddons#31]
I don't know if it is intended, but Amazon links are not cleaned. I have noticed this behavior by testing the links shown on a similar addon page:
https://addons.mozilla.org/fr/firefox/addon/link-cleaner/

![screenshot](https://i.imgur.com/BqjBbzP.png)

I don't care about skipping redirections, because I use another more general addon, which is not limited to Facebook, Steam and Reddit. However, I wonder whether there is a good reason not clean Amazon URLs. Maybe it interferes with the shopping process? I remember I tested Link Cleaner earlier this year and thought that the addon was too brutal and would break some websites.

**Comment by Smile4ever** [comment]
Hi. Thanks for opening an issue about https://www.amazon.com/AmazonBasics-Type-C-USB-Male-Cable/dp/B01GGKYQ02/ref=sr_1_1%3Fs=amazonbasics&srs=10112675011&ie=UTF8&qid=1489067885&sr=8-1&keywords=usb-c

I actually do a check before stripping all parameters off to prevent breaking certain URLs.

Could you provide me with the following information?
* The version of Neat URL you're using
* The parameters that are visible in the options
* Which Firefox version and operating system

**Comment by woctezuma** [comment]
Neat URL 2.0.3

Parameters: the default ones plus 3 for Humble Bundle (hmb_campaign, hmb_source, hmb_medium).

`utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_reader, utm_place, utm_userid, utm_cid, ga_source, ga_medium, ga_term, ga_content, ga_campaign, ga_place, yclid, _openstat, fb_action_ids, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map, gs_l, pd_rd_r@amazon.*, pd_rd_w@amazon.*, pd_rd_wg@amazon.*, _encoding@amazon.*, psc@amazon.*, ved@google.*, ei@google.*, sei@google.*, gws_rd@google.*, cvid@bing.com, form@bing.com, sk@bing.com, sp@bing.com, sc@bing.com, qs@bing.com, pq@bing.com, feature@youtube.com, gclid@youtube.com, kw@youtube.com, $/ref@amazon.*, hmb_campaign, hmb_source, hmb_medium`

Firefox 55.0.3 (64 bits), Windows 10 Pro 64 v.1607 v.14393.1593 (bits)

**Comment by woctezuma** [comment]
When I click on your link, the addon works.

[The link](https://www.amazon.com/AmazonBasics-Type-C-USB-Male-Cable/dp/B01GGKYQ02/ref=sr_1_1%3Fs=amazonbasics&srs=10112675011&ie=UTF8&qid=1489067885&sr=8-1&keywords=usb-c) becomes [this URL](https://www.amazon.com/AmazonBasics-Type-C-USB-Male-Cable/dp/B01GGKYQ02).

**Comment by Ghost8652** [comment]
Is there any update? I'm having this issue too.

**Comment by Smile4ever** [comment]
There will be an update this weekend which fixes these issues on Amazon product pages.

**Comment by Smile4ever** [comment]
Fixed by https://github.com/Smile4ever/firefoxaddons/commit/98dba5e93ba5b73dcacbfc4a2fb030d76c496d04 which is available in Neat URL 2.1.0.
