### ISSUE TITLE
[Neat URL] Parameter after last delimiter is ignored

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#32]
Hi

Last parameter in settings is ignored.
Example: `utm_source, utm_medium, utm_term`
`utm_term` will be ignored

If semicolon is used at the end, then if works.
Example: `utm_source, utm_medium, utm_term,`

Cheers

**Comment by Smile4ever** [comment]
Works for me, no issue whatsoever.
- Make sure you don't forget to save the parameters.
- A sample URL which has this problem would help.

**Comment by crssi** [comment]
I have tested again and here doesn't work and I haven't forgot to save.
To make the last parameter work here, it must be followed with `,`.
I am on FF 55.0.3, x64, Win 10. Maybe is the problem in FF version?

**Comment by Smile4ever** [comment]
Are you using Neat URL 2.0.3?

**Comment by crssi** [comment]
Yes

**Comment by Smile4ever** [comment]
I tested using Firefox 55.0.3, x64, Win 10 and Neat URL 2.0.3 and couldn't reproduce.

I used these parameters:
utm_source, utm_medium, utm_campaign

For this sample URL:
http://www.boredpanda.com/siblings-childhood-photo-recreation/?page_numb=6&utm_source=cfrogf&utm_medium=link&utm_campaign=omg

What URL do you use?

**Comment by crssi** [comment]
I have lost the link with UTMs.
But I can replicate with any.
[http://www.imdb.com/title/tt5999770/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=2750721702&pf_rd_r=1C3ZC4E3GQVZRWT6WX6F&pf_rd_s=right-2&pf_rd_t=15061&pf_rd_i=homepage&ref_=hm_otw_t5](http://www.imdb.com/title/tt5999770/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=2750721702&pf_rd_r=1C3ZC4E3GQVZRWT6WX6F&pf_rd_s=right-2&pf_rd_t=15061&pf_rd_i=homepage&ref_=hm_otw_t5)

Parameters (some just added to default):
`utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_reader, utm_place, utm_userid, utm_cid, ga_source, ga_medium, ga_term, ga_content, ga_campaign, ga_place, yclid, _openstat, fb_action_ids, fb_action_types, fb_ref, fb_source, action_object_map, action_type_map, action_ref_map, gs_l, pd_rd_r@amazon.*, pd_rd_w@amazon.*, pd_rd_wg@amazon.*, _encoding@amazon.*, psc@amazon.*, ved@google.*, ei@google.*, sei@google.*, gws_rd@google.*, cvid@bing.com, form@bing.com, sk@bing.com, sp@bing.com, sc@bing.com, qs@bing.com, pq@bing.com, feature@youtube.com, gclid@youtube.com, kw@youtube.com, $/ref@amazon.*,pf_rd_m,pf_rd_p,pf_rd_r,pf_rd_s,pf_rd_t,pf_rd_i,ref_,
`

Just remove `,` at the end. Save. And try again upper link.

If you can't replicate, let me know. I will retry again with clean FF profile with only Neat URL extension.

Cheers

**Comment by Smile4ever** [comment]
I followed your instructions but was not able to reproduce.

**Comment by crssi** [comment]
OK... thank you.
Will do a test with plain vanilla FF + Neat URL as the only installed extension later this evening and report back ASAP.

Cheers

**Comment by crssi** [comment]
Even faster. Found it.
It not `,` problematic, but I had in config a "carriage return" on the end. In that case the last parameter is ignored.

Cheers

**Comment by Smile4ever** [comment]
If someone encounters the same problem, I will fix the carriage return problem. Otherwise I will just leave it like it is. Thanks for testing!

**Comment by crssi** [comment]
Wouldn't it will be easier to just trim the whole text area?

Cheers and thank you for your work
