### ISSUE TITLE
[Neat URL] Improvement: using wildcard in parameter

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#33]
Can be done something to improve parameter wildcards.

Example: 
Instead of
`utm_source, utm_medium, utm_term`

Possibility to use the following would be really nice:
`utm_*`

Cheers

**Comment by Smile4ever** [comment]
This feature is planned for a next release.

**Comment by crssi** [comment]
@Smile4ever is this implemented now?
Thank you and cheers

**Comment by Smile4ever** [comment]
Not yet. It's on the planning.

**Comment by Smile4ever** [comment]
Added in Neat URL 3.0.0 which is available on addons.mozilla.org. See the README for usage.
