### ISSUE TITLE
[Translate Now] DeepL support

### ISSUE THREAD

**Issue by abba23** [Smile4ever/firefoxaddons#34]
The DeepL Translator (https://www.deepl.com/translator) is a new translation service that uses convolutional instead of recurrent neural networks and delivers much better translations than either Google or Bing.

**Comment by woctezuma** [comment]
I would be interested as well. I have tested this translator a bit (English to French), and it is really impressive.

**Comment by Smile4ever** [comment]
It's impressive indeed. I will add support in a next release.

**Comment by Smile4ever** [comment]
It will be available in Translate Now 3.1.0 which has been submitted to addons.mozilla.org.

Changes:
https://github.com/Smile4ever/firefoxaddons/commit/3d9965459c1a7f1e001506061c99d8e7c4acaa3b

**Comment by Smile4ever** [comment]
It is now available. Enjoy it!

**Comment by woctezuma** [comment]
Thank you!

**Comment by Smile4ever** [comment]
You're right. 3.1.1 contains the fix.
https://github.com/Smile4ever/firefoxaddons/commit/fd09e9bdea94a1cb56f84cccaf0b2d9d096befc2
