### ISSUE TITLE
[Neat URL] Question: Which types of requests are covered and "debug"?

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#36]
Which types of requests are covered by Neat URL?
`Document, Sub document, Stylesheet, Script, Image, Object, PlugIN, XMLHttpRequest (XHR), XBL, XSLT, Ping, Beacon, XML DTD, Font, Media, WebSocet, CSP report, Imageset, Web Manifest, Other`

Can I see anywhere what was originally requested and what was really requested after Neat URL has done its job?

Thank you buddy and cheers

**Comment by Smile4ever** [comment]
Neat URL covers all requests that Firefox makes, assuming these are also passed to webRequest. See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest

You can't really see that - but if you download the code, you should look for details.url in background.js (the requested URL) and leanURL (the cleaned URL, also in background.js).

**Comment by crssi** [comment]
Thank you

**Comment by crssi** [comment]
Can you write changes to debug console?

**Comment by Smile4ever** [comment]
Added in Neat URL 3.0.0 which is available on addons.mozilla.org. Just go to the options and activate it there :)

**Comment by crssi** [comment]
Thank you, you are a TZAR :+1:
