### ISSUE TITLE
Privacy Policy (or policies)

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [Smile4ever/firefoxaddons#37]
Hi @Smile4ever 

One thing I am in the process of doing with the ghacks user.js [wiki page for extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions) is to add **Privacy Policy** links (like below). If an extension has one that respects privacy, awesome, if not, no such "badge" (and if it has one one that stinks, it will not be recommended). 

We currently have Neat URL listed (we just focus on privacy/tracking/anti-fingerprinting/security)

Would you consider creating a simple AMO Privacy Policy (or GitHub wiki page, or root md file)? Cheers.

* [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) <sup>✔ [Privacy](https://github.com/gorhill/uBlock/wiki/Privacy-policy)</sup> | [GitHub](https://github.com/gorhill/uBlock) << GitHub example
* [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes/) <sup>✔ [Privacy](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/)</sup> | [GitHub](https://github.com/Synzvato/decentraleyes)  << AMO example

**Comment by Smile4ever** [comment]
I've added a privacy policy for Neat URL. Basically it says no data is ever submitted to a third party. You can see it on AMO.
