### ISSUE TITLE
[Neat URL] BuzzFeed URLs remain unclean

### ISSUE THREAD

**Issue by ronjouch** [Smile4ever/firefoxaddons#39]
*"NOTABUG/WONTFIX, THAT'S EXPECTED BEHAVIOR, HOW WOULD ANYTHING BUZZFEED BE CLEAN?!"*, I hear you shout 😄.

Now, to the bug: open https://www.buzzfeed.com/bensmith/theres-blood-in-the-water-in-silicon-valley in a Firefox 57 with Neat URL on.

Expected: URL stays clean.
Actual: URL gets a `utm_term` parameter after loading.

Looks like the `utm_term` param is added a while after loading, is there anything Neat URL can do?

**Comment by Smile4ever** [comment]
Not sure if this is fixable. I will investigate.

**Comment by Smile4ever** [comment]
I'm afraid nothing can be done here that's reasonable. Changing the URL after 3 seconds to it's sane form works for half a second, after that BuzzFeed reverts to the ugly URL.

**Comment by ronjouch** [comment]
> *I'm afraid nothing can be done here that's reasonable. Changing the URL after 3 seconds to its sane form works for half a second, after that BuzzFeed reverts to the ugly URL.*

@Smile4ever yup that's what I was expecting 🙂. Thanks for having a look!
