### ISSUE TITLE
Multi Links Plus - Left click enable/disable in status bar

### ISSUE THREAD

**Issue by alexhk** [Smile4ever/firefoxaddons#4]
I used to be able to enable/disable Multi Links with a simple left click on the Addon Bar (it would turn from green to gray and vice versa). This seems not to work any longer. I am on Multi Links Plus 3.6.2 and (not sure if that has anything to do with it) I changed to Firefox 64bit a few weeks ago, using latest version 47.0.1. 

Actually after starting Firfox it's still green with Multi Links Plus active. 

![2016-07-08_12h43_08](https://cloud.githubusercontent.com/assets/1495412/16677539/ac0084fc-4509-11e6-968c-4223e84ed6a3.jpg)

If I click once, it turns gray. 

![2016-07-08_12h40_45](https://cloud.githubusercontent.com/assets/1495412/16677504/592efb46-4509-11e6-939d-5ba1fa6605fc.jpg)

But it is still active (I can still select multiple links).

If I click again, nothing changes, it doesn't turn green again. The expected would  would toggling between green and grey (enabled/disabled).

Also, as a long term user I just supported you with a small donation via the Add-On page, thanks for keeping this add-on alive for such a long time!

**Comment by Smile4ever** [comment]
I will look into this, thanks for letting me know. I found another issue, it's probably related. You can add a Multi Links Plus icon on your toolbar via Customize toolbar. That's the workaround for now.

I appreciate that, thanks +1

**Comment by Smile4ever** [comment]
"But it is still active (I can still select multiple links)."
I'm not able to reproduce this, please update to 3.6.3 and try again as that may already solve the issue.

If that doesn't work, go to Options -> Advanced and enable "Force context menu cancellation". Does that solve the issue?

**Comment by alexhk** [comment]
Updated to 3.6.3. Still the same problem.
Also no difference if I use "Force context menu cancellation". 

To recap: originally my icon in the "Addon bar" is with green and red (meaning MLP is enabled). When I click on it, it grays out. But it is still enabled (I can still use MLP). When I click again nothing happens (it doesn't become green and red again).

**Comment by alexhk** [comment]
Ha, I just added Multi Links Plus icon to my toolbar using "customize" as you described, and now enabling and disabling it also works by clicking on the icon in the "Addon bar" (I still have "Force context menu cancellation" checked from before). 

However, once I remove it again from the toolbar, disabling and enabling via icon in the "Addon bar" also stops working again.  

I still have Hope that extra info helps.

**Comment by Smile4ever** [comment]
I will look into it, thanks for the information.
