### ISSUE TITLE
[Translate Now] DeepL: no submission the 1st time

### ISSUE THREAD

**Issue by woctezuma** [Smile4ever/firefoxaddons#41]
Let us say I want to translate a paragraph.

![Text to translate](https://i.imgur.com/3jlnojT.png)

The first time I submit it using the context menu, I get the following: big font and no translation, unless I press "Enter".
![Not OK](https://i.imgur.com/JvNc31S.png)

If I don't want to press "Enter", I can go back to the tab with the paragraph still selected and use the context menu again. Then I get the expected behavior (notice the small font and the translated text).
![OK](https://i.imgur.com/FgFMl6v.png)

It is weird because it happens quite often, but not always. I don't know what causes it.

**Comment by Smile4ever** [comment]
I was not able to reproduce the issue.

* Which version of Firefox are you using?
* Double check that you're using Translate Now 3.1.2.
* Does this happen always with a certain site?

If you know exactly when it fails, I can look at it in detail. I think it will be a timing issue.

Could you please do the following?
* When you have a DeepL page open, change the destination language to something else (=not the current destination language).
* Open the Translate Now options. Set your source language to "Detect automatically" and set your destination language to French.
* Close all DeepL tabs.
* Select some text and translate it with DeepL. If you encounter the text being big, could you check if the destination language was changed? If it works this time, repeat these steps a few times.

**Comment by woctezuma** [comment]
- Firefox 55.0.3 (64 bits)
- Translate Now 3.1.2
- I think it only happens when it is trying to figure out the input language. So, it might be just me being impatient.

**Comment by Smile4ever** [comment]
Hi. I have managed to reproduce the issue with a lot of accuracy. I have spent quite a while to come up with a decent solution. The solution is implemented in https://github.com/Smile4ever/firefoxaddons/commit/8ae7e61d1b76285d06f7d2aa56723411aa9f6efd and will be part of Translate Now 3.1.3 which is now available on addons.mozilla.org.

**Comment by Smile4ever** [comment]
Translate Now 3.1.3 is now available on addons.mozilla.org.

**Comment by woctezuma** [comment]
Thanks!
