### ISSUE TITLE
[Neat URL] additions to blocked parameters

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#43]
FYI. This is NOT and "issue", only informational. @Smile4ever close this "issue" at your will. ;)
I have a little extended the blocked parameters to (all together):
`$/ref@amazon.*, _encoding@amazon.*, _hsenc, _hsmi, _openstat, action_object_map, action_ref_map, action_type_map, algo_expid, algo_pvid, aqs, bav, bih, biw, btsid, bvm, cn, cp, csi, cvid@bing.com, dpr, dq, ech, ei@google.*, fb_action_ids, fb_action_types, fb_ref, fb_source, feature@youtube.com, form@bing.com, forward, ga_campaign, ga_content, ga_medium, ga_place, ga_source, ga_term, gclid@youtube.com, gs_gbg, gs_l, gs_mss, gs_rn, gws_rd@google.*, hmb_campaign, hmb_medium, hmb_source, iact, icid, iid, ijn, kw@youtube.com, mc_cid, mc_eid, mkt_tok, ncid, ndsp, nid, nr_email_referer, oq, pbx, pd_rd_r@amazon.*, pd_rd_w@amazon.*, pd_rd_wg@amazon.*, pf, pf_rd_i, pf_rd_m, pf_rd_p, pf_rd_r, pf_rd_s, pf_rd_t, pq, pq@bing.com, prmd, psc@amazon.*, psi, qs@bing.com, ref_, refsrc, sa, sc@bing.com, sclient, scroll, sei@google.*, sk@bing.com, sp@bing.com, sr_share, stick, tbnid, utm_campaign, utm_cid, utm_content, utm_medium, utm_name, utm_place, utm_pubreferrer, utm_reader, utm_source, utm_swu, utm_term, utm_userid, utm_viz_id, ved, ved@google.*, vero_conv, vero_id, vet, ws_ab_test, yclid, yv`

To whom it might concern
cheers

**Comment by Smile4ever** [comment]
Thanks a lot for sharing your parameters!

**Comment by Smile4ever** [comment]
Some of these parameters have been added to Neat URL 3.0.0, others have been added to the README. Thank you!
