### ISSUE TITLE
[Neat URL] Hash fragment is getting removed

### ISSUE THREAD

**Issue by kirill9000** [Smile4ever/firefoxaddons#47]
I'm using Neat URL 2.1.2.

Steps to reproduce:
1. Add rule `test@github.com`.
2. Go to `https://github.com/Smile4ever/firefoxaddons/tree/master/Neat%20URL-webext?test=1#neat-url`.
3. Result: `https://github.com/Smile4ever/firefoxaddons/tree/master/Neat%20URL-webext` (without fragment).

PS Off-topic, regarding your URL-splitting code - wouldn't it be simpler to use [URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)? Just a suggestion.

**Comment by Smile4ever** [comment]
I have worked on this issue this evening and it required some neater code in order to be fixable. URL() helped a lot with that. Thank you.

I will inform you when I consider this issue fixed and in which Neat URL version it will appear.

**Comment by Smile4ever** [comment]
Fixed in Neat URL 3.0.0 which is available on addons.mozilla.org.

**Comment by kirill9000** [comment]
Yep, works fine now. Thanks!
