### ISSUE TITLE
[Neat URL] download link broken for https://www.java.com/en/download/windows-64bit.jsp

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#49]
When Neat URL is active or has any blocked parameter in the settings, then download at site [https://www.java.com/en/download/windows-64bit.jsp](https://www.java.com/en/download/windows-64bit.jsp) doesn't work.

If you delete all the blocked parameters in the settings then download works.
If you enter any blocked parameter, for example only "blahblahblah", then download doesn't work.

Its not that download that botheres me, but it must be something deeper in Neat URL that doesn't work well. Maybe the URL() function?

Cheers

**Comment by crssi** [comment]
Same happens with youtube video that does not start [https://www.youtube.com/watch?v=94ukUblLwU4](https://www.youtube.com/watch?v=94ukUblLwU4)
When Neat URL disabled or without any blocked parameters, it works. If I add only one parameter, for example "xxxxx", it does not work anymore,
Note: when video is cached, after succesfull play, it will always work until FF restart,

**Comment by Smile4ever** [comment]
I will be handling #52 in Neat URL 3.0.1 to fix this problem.
