### ISSUE TITLE
[Neat URL] Version 3.0.0 stops access to https://outlook.manchester.ac.uk 

### ISSUE THREAD

**Issue by caglarkoksal** [Smile4ever/firefoxaddons#50]
When I try to access `https://outlook.manchester.ac.uk` I receive this error:

```
The page cannot be displayed
--
Explanation: There is a problem with the page you are trying to reach and it cannot be displayed.
Try the following:                
Refresh page: Search for the page again by clicking the Refresh button. The timeout may have occurred due to Internet congestion. 
Check spelling: Check that you typed the Web page address correctly. The address may have been mistyped. 
Access from a link: If there is a link to the page you are looking for, try accessing the page from that link.                       
Technical Information (for support personnel)                
Error Code: 500 Internal Server Error. The parameter is incorrect. (87)
```

And this is the error URL: `https://outlook.manchester.ac.uk/CookieAuth.dll?GetLogon%3Fcurl=Z2FowaZ2F&reason=0&formdir=1`

If I disable Neat URL and login to my emails, I can access `https://outlook.manchester.ac.uk` while Neat URL is enabled so long as my session is active. If I log out, I need to disable Neat URL to open login page.

The issue was introduced in version 3.0.0

**Comment by crssi** [comment]
It the same "behind the scene"  reason, I believe, as I have posted [here](https://github.com/Smile4ever/firefoxaddons/issues/49#issue-263709623)

**Comment by caglarkoksal** [comment]
My issue was resolved by itself i.e. I didn't change anything but two hours ago the problem was gone. So I will close this issue.

**Comment by ronjouch** [comment]
What? Well, not for me. Re-opening #52, then 😄
