### ISSUE TITLE
[Neat URL v3.1.0] clarification regarding URL request types

### ISSUE THREAD

**Issue by atomGit** [Smile4ever/firefoxaddons#53]
the addition of allowing the user to decide what request types are filtered is interesting, except i don't know what the heck to do with it :)

in your opinion, and given i'm concerned with privacy (i use the ghacks user.js in combo with my own) but am willing to sacrifice a bit of privacy for a somewhat carefree browsing experience, what request types should be filtered? in other words, what filters are unlikely to cause a lot of breakage? i don't mind fiddling around with some sites on occasion to get them to work, but i don't want to be constantly bothered with it 

btw, i like the content on your website - you seem to be pretty busy and knowledgeable for a young fella :)

**Comment by Smile4ever** [comment]
You can probably add most of the request types below without being annoyed every day. You can ask for every issue you encounter to investigate so I can look if this is something Neat URL should know about.

I have set "useful" when it's likely to contain some kind of (tracking) mess
I have set "doubtful" when I think it's not worth it

To answer your question:

beacon
* Requests sent through the Beacon API.
* Useful

csp_report
* Requests sent to the report-uri given in the Content-Security-Policy header, when an attempt to violate the policy is detected.
* Doubtful

font
* Web fonts loaded for a @font-face CSS rule.
* Doubtful

image
* Resources loaded to be rendered as image, except for imageset on browsers that support that type (see browser compatibility below).
* Doubtful

imageset
* Images loaded by a picture element or given in an img element's srcset attribute.
* Doubtful

main_frame
 * Top-level documents loaded into a tab.
* Useful (default)

media
* Resources loaded by a  video or  audio element.
* Doubtful

object
* Resources loaded by an object or embed element.
* Browsers that don't have a dedicated object_subrequest type (see browser compatibility below), also label subsequent requests sent by the plugin as object.
* Doubtful

object_subrequest
* Requests sent by plugins.
* Doubtful

ping
* Requests sent to the URL given in a hyperlink's ping attribute, when the hyperlink is followed.
 *Browsers that don't have a dedicated beacon type (see browser compatibility below), also label requests sent through the Beacon API as ping.
* Useful

script
* Code that is loaded to be executed by a <script> element or running in a Worker.
* Doubtful

stylesheet
* CSS stylesheets loaded to describe the representation of a document.
* Doubtful

sub_frame
* Documents loaded into an <iframe> or <frame> element.
* Useful

web_manifest
* Web App Manifests loaded for websites that can be installed to the homescreen.
* Doubtful

websocket
* Requests initiating a connection to a server through the WebSocket API.
* Doubtful

xbl
* XBL bindings loaded to extend the behavior of elements in a document.
* Doubtful

xml_dtd
* DTDs loaded for an XML document.
* Doubtful

xmlhttprequest
* Requests sent by an XMLHttpRequest object or through the Fetch API.
* Doubtful

xslt
* XSLT stylesheets loaded for transforming an XML document.
* Doubtful

other
* Resources that aren't covered by any other available type.
* Maybe

> btw, i like the content on your website - you seem to be pretty busy and knowledgeable for a young fella :)

Thank you.

**Comment by atomGit** [comment]
perfect - thanks - hopefully helpful to others as well
i'll go with all those you marked "useful"

**Comment by atomGit** [comment]
one more thing ... you might want to add that to your wiki and/or your AMO page maybe?

**Comment by Smile4ever** [comment]
https://github.com/Smile4ever/firefoxaddons/wiki/Neat-URL

**Comment by crssi** [comment]
Over image and xmlhttprequest all kind of shit load is calling back.

For example:
maps.google.com, youtube over XHR
youtube, facebook over IMG

**Comment by Smile4ever** [comment]
I've edited the wiki page to reflect that.
