### ISSUE TITLE
[Neat URL] last update (3.1.0) broke youtube

### ISSUE THREAD

**Issue by Zaphkiel** [Smile4ever/firefoxaddons#54]
since the last update half of my youtube are broken, they are simple going into an infinite loop 
after i disabled the extension youtube works fine
removing the parameters doesnt help either

**Comment by Smile4ever** [comment]
Could you provide me a sample URL?

**Comment by Zaphkiel** [comment]
[https://www.youtube.com/watch?v=Gi4CTosY1WI](url) for example it doesn't load

**Comment by Smile4ever** [comment]
I cannot reproduce it. Could you enable logging in the addon options and check what text it logs to the Browser Console?

**Comment by Zaphkiel** [comment]
[log.txt](https://github.com/Smile4ever/firefoxaddons/files/1373354/log.txt)

**Comment by Smile4ever** [comment]
Thanks. I don't see Neat URL doing something in those logs though.

Could you provide a screenshot of the logging items as well? I'm interested in these log items:
* "cancelling {url}"
* "Neat URL (type {type}): {originalurl} has been changed to {cleanurl}"

They should come from background.js.

**Comment by Zaphkiel** [comment]
my bad, i had v3.0.0 not 3.1.1 which is the last one and seems to fix my problem after updating
thanks for help

**Comment by Smile4ever** [comment]
Actually the problem was fixed in 3.1.0. Since you said latest I assumed 3.1.0 but it seems my assumption was wrong. No problem and thanks for reaching out!
