### ISSUE TITLE
[Neat URL] Tracking domains blocking

### ISSUE THREAD

**Issue by kirill9000** [Smile4ever/firefoxaddons#58]
Sorry to say this, but I think this feature should be removed. It is out of purpose for Neat URL and it's current implementation via array iteration is awfully inefficient. Why would you want to reinvent it anyway? There are already several ad-blocking extensions which do exactly that and do it fast.

**Comment by Smile4ever** [comment]
I mainly added this feature to prevent issues with tracking URLs which can use very weird URL formats. I thought about skipping these domains hardcoded inside the code, but I wanted to offer users the option to change these and meanwhile make it more transparent what Neat URL does.

Do you think it's slowing down Neat URL too much?

What addons would you suggest to use instead?

**Comment by kirill9000** [comment]
>which can use very weird URL formats

Could you give an example?

>Do you think it's slowing down Neat URL too much?

Yes. Especially if you plan to add more domains to the list.

>What addons would you suggest to use instead?

uBlock Origin.

**Comment by Smile4ever** [comment]
This feature has been removed and it has been replaced by a similar feature "Blacklist" which does not cancel requests, but instead skips certain domains or links. Both the adding of the blacklist feature and removal of Block tracking domains have happened in Neat URL 3.2.0.
