### ISSUE TITLE
[Neat URL] Improvement suggestion for "URL request types"

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#59]
To avoid typos and/or confusion, can you implement list of URL request types with check boxes?

Cheers

**Comment by Smile4ever** [comment]
I won't do this, I'm sorry. I feel the current solution is very flexible and if you're editing this list you should know what you're doing.

**Comment by crssi** [comment]
Understood.
Thank you anyway

**Comment by crssi** [comment]
But still, it would be nice touch.
There are also XHR and IMAGE, where all kind of shitload of data is transfered (like fingerprint hashes, etc.)

**Comment by Smile4ever** [comment]
Other request types handled in #53
