### ISSUE TITLE
Multi Links Plus does not work on yahoo.co.jp

### ISSUE THREAD

**Issue by user20161012** [Smile4ever/firefoxaddons#6]
This add-on can not use in the yahoo.co.jp-mail.
3.0.2 is available.

**Comment by Smile4ever** [comment]
- What do you mean with 3.0.2 is available? Multi Links Plus 3.0.2 is very old, you should have Multi Links Plus 3.7.0 or higher to get all the fixes.
- What does not work? You can't get the Multi Links Plus rectangle?

**Comment by user20161012** [comment]
yes,  Multi Links Plus 3.8.0  ~　3.5.0 is not able to  get link. Rectangle is not displayed.

Multi Links Plus 3.0.2 is rectangle appears.

**Comment by user20161012** [comment]
3.9.0  is also　not working https://outlook.live.com. 
You do not read the link of the body of the email.

ヤフーメールとOutlookメールの本文のリンクも取得してくれません。

**Comment by Smile4ever** [comment]
Please test with these about:config values:
extensions.multilinks@plugin.ContextMenuCancellationTextArea to false
extensions.multilinks@plugin.ContextMenuCancellationInput to false
extensions.multilinks@plugin.ContextMenuCancellationHTML to false

Does the issue go away?

**Comment by user20161012** [comment]
It is still not resolved...
Therefore, we attempted to initialize the firefox. Add-on it is one.
Do you have things to do to the other?

まだ解決しません。。。
firefoxの新しいプロファイルで試しても駄目でした。
ほかには解決方法ありませんか？
firefox49.0.2　windows7 64bit

**Comment by Smile4ever** [comment]
I was able to reproduce this on http://outlook.live.com. I will track down the cause and report back.

**Comment by Smile4ever** [comment]
I think Multi Links Plus 3.9.2 resolves the issue for both Outlook.com and Yahoo! Japan. Please verify if it works for you. You can get Multi Links Plus 3.9.2 here once it's approved: https://addons.mozilla.org/nl/firefox/addon/multi-links-plus/versions/3.9.2
