### ISSUE TITLE
[Neat URL] Improvement suggestion for icon

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#60]
Can you make icon red color for example, which would not reset back to default after some time period, on the tabs where Neat URL makes changes?
It would be more visible.

**Comment by Smile4ever** [comment]
I'm open to pull requests 😉

**Comment by Smile4ever** [comment]
What's an acceptable time to reset the icon for you? Three seconds?

**Comment by gwarser** [comment]
Never? Or maybe create badge with number of altered URLs for current page.

**Comment by crssi** [comment]
Exactly, never on that page/tab.

**Comment by Smile4ever** [comment]
Implemented in 3.2.0.
