### ISSUE TITLE
[Neat URL] Issue with double question mark rewrited to single question mark, but it should not

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#66]
When visiting [www.aliexpress.com](www.aliexpress.com) the page style and scripts are broken, since every double question `??` in the link is rewritten to single question `?`.
If you clear all blocked parameters in the settings, then it works.
If you place just one blocked parameter (try with something nonexisting like: blahblahblahblah), it is broken, even if you clear all the URL request types.

This was not the case with Neat URL 2.1.2 or lower.

**Comment by Smile4ever** [comment]
In the next release, I will skip URLs that contain two ?? signs. That will eliminate a whole category of problems.

Types empty means all types right now. I will change that to no rewriting for the new release.

**Comment by crssi** [comment]
Huh... isn't that radical? :(
I would like to clean those URLs, without rewriting ?? with ? and not simply skipping them.

**Comment by Smile4ever** [comment]
Skipping those URLs is all we can do, I'm afraid. It would lead us too far and it would complicate Neat URL more than needed. I've skipped the urls containing ?? in 3.2.0.
