### ISSUE TITLE
[Neat URL] forbes.com url tracking

### ISSUE THREAD

**Issue by octoberfest** [Smile4ever/firefoxaddons#67]
When visiting forbes.com, it uses a unique identifier such as #46fdy9dh73fd at end of each link/url you visited to track user. For instance:
`https://www.forbes.com/sites/kerryadolan/2017/03/20/forbes-2017-billionaires-list-meet-the-richest-people-on-the-planet/#46fdy9dh73fd`

How do you use Neat URL to clean/block that unique identifier?

**Comment by Smile4ever** [comment]
Hi. Neat URL can clean URLs which add #6eb814f262ff at first, but do not force #6eb814f262ff to be added again after you deleted it from the URL. Therefore #6eb814f262ff will not work on Forbes, it's added again after removal (you can get removal for 0.1 seconds by including #6eb814f262ff in the blocked parameters section)

**Comment by gwarser** [comment]
Fragment identifiers are not sent to the server in URL. They are handled by browser only. If they are preserved, then probably are stored and send in some other way (cookies?).

**Comment by Smile4ever** [comment]
>Fragment identifiers are not sent to the server in URL. They are handled by browser only. 

I know that.

> If they are preserved, then probably are stored and send in some other way (cookies?).

I don't know how it works, but they probably use use JavaScript after the page has loaded.

Even if I remove them after a while by rewriting the URL inside Neat URL, they come back. So there's nothing Neat URL can do here, I'm afraid.
