### ISSUE TITLE
[Neat URL] unknown breakage (usage of URL constructor)

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#73]
I am visiting web page:
`https:/somedomain.com/weservice.exe?SID=1255165669+FID=5234+OP=SEARCH+FACTORY=cr+KEEP.where_clause=%28status%20like%20%27RE%25%27%20OR%20status%20like%20%27%25comp%25%27%20OR%20status%20%3D%27Z_CPL%27%29%20AND%20tenant.name%3D%27ServiceDesk%27%20`

Which is rewrited to:
`https:/somedomain.com/weservice.exe?SID=1255165669+FID=5234+OP=SEARCH+FACTORY=cr+KEEP.where_clause=%28status+like+%27RE%25%27+OR+status+like+%27%25comp%25%27+OR+status+=%27Z_CPL%27%29+AND+tenant.name=%27ServiceDesk%27+`

despite that I have none defined `blocked parameters` within the visited URL scope.

Even when I clear all `blocked parameters` and add only one like `blahblahblah` the result is the same, leading to breakage.

Until this is resolved I have added domain to `domain blacklist`.
Let me know when changes made and I can test for you again.

Cheers

**Comment by crssi** [comment]
Anything new, some new ideas?

**Comment by Smile4ever** [comment]
Not yet.
