### ISSUE TITLE
[Neat URL] Switching between '.com' and local tld on Google is broken

### ISSUE THREAD

**Issue by gwarser** [Smile4ever/firefoxaddons#76]
If I go to https://www.google.com/ browser will redirected me to my localized Google search page - https://www.google.pl/
Link will be shown on bottom right corner - Use Google.com
Clicking on this link have no desired effect - page is only refreshed.
Clicking on this link should redirect me permanently to '.com' version of page.

This is because `gws_rd@google.*` rule.

**Comment by Smile4ever** [comment]
Fixed in Neat URL 4.0.0 which is now available on addons.mozilla.org.
