### ISSUE TITLE
Neat URL - Uanble to change user on Rainloop webmail

### ISSUE THREAD

**Issue by Nono-m0le** [Smile4ever/firefoxaddons#79]
Since 2 or 3 weeks now, I was unable to switching users on my Rainloop webmail.

**Comment by Smile4ever** [comment]
You can use the blacklist for now to circumvent the problem you're having. I will investigate this.

**Comment by Smile4ever** [comment]
What do you see in the browser console when you enable the logging feature on the options page when trying to switch users on your Rainloop webmail?

**Comment by Nono-m0le** [comment]
is this what you are looking for ? (screenshot from the web console on "Web Developper" module in FF) https://i.imgur.com/BR69KQ5.png

**Comment by Smile4ever** [comment]
No, the browser console is different from the web console. We need the browser console, which can be accessed by Ctrl+Shift+J. Don't forget to turn on Neat URL logging first and clicking on "Save preferences".

**Comment by Nono-m0le** [comment]
here we are then : 
Empty string passed to getElementById().  libs.min.js:1:34763
Empty string passed to getElementById().  libs.min.js:1:34763
"Neat URL (type main_frame): https://mail.domain.tld/?/Change/&q[]=/__EbCCjeXJrn43xKGKXzkxS5HV6rxaOBQ4cn7f7-tMOKu8XVudQmc1QXUjytCtqTqCaMfEQspW1pQKKgcCheV98rqSe4sEF3Q67AUKkxTj0qgcNyWp0XPhNo-bry1QDT6CZmkVSY2CFZtJTUZJmR0af0hzcpyUS0Trzj6QwQyNColq7RHLH9IDsYge78Rt1tIGdzdT7W04PIzUxKsD-SSkffnjlFfujCxsExUO4asS75k1EsLi4CuhuEGRaPyDSDP4oIGyyPC0Ddn5hLJyOxiqHrkRzpmtD7KoOMJiDGxiQI5UwUy0LZXb_imeoaI_lJu5qbD5OAnGpgIvsMA2rwYSU528NYqd9OKzckb7-nlfuk/mail2%40domain2.tld/ has been changed to https://mail.domain.tld/?/Change/=&q%5B%5D=/__EbCCjeXJrn43xKGKXzkxS5HV6rxaOBQ4cn7f7-tMOKu8XVudQmc1QXUjytCtqTqCaMfEQspW1pQKKgcCheV98rqSe4sEF3Q67AUKkxTj0qgcNyWp0XPhNo-bry1QDT6CZmkVSY2CFZtJTUZJmR0af0hzcpyUS0Trzj6QwQyNColq7RHLH9IDsYge78Rt1tIGdzdT7W04PIzUxKsD-SSkffnjlFfujCxsExUO4asS75k1EsLi4CuhuEGRaPyDSDP4oIGyyPC0Ddn5hLJyOxiqHrkRzpmtD7KoOMJiDGxiQI5UwUy0LZXb_imeoaI_lJu5qbD5OAnGpgIvsMA2rwYSU528NYqd9OKzckb7-nlfuk/mail%40domain2.tld/"  background.js:531
Successfully compiled asm.js code (total compilation time 41ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))  openpgp.min.js
Successfully compiled asm.js code (total compilation time 12ms; not stored in cache (too small to benefit))  openpgp.min.js
Successfully compiled asm.js code (total compilation time 7ms; not stored in cache (too small to benefit))  openpgp.min.js
Successfully compiled asm.js code (loaded from cache in 5ms)  openpgp.min.js
Successfully compiled asm.js code (total compilation time 7ms; not stored in cache (too small to benefit))  openpgp.min.js
Successfully compiled asm.js code (total compilation time 8ms; not stored in cache (too small to benefit))  openpgp.min.js

**Comment by Smile4ever** [comment]
If I look at the logging, this might be fixed already with Neat URL 4.0.0 which will soon be released. You can test whether it solves your issue:
* Download this ZIP file: https://github.com/Smile4ever/firefoxaddons/blob/master/Neat%20URL-webext/web-ext-artifacts/neat_url-4.0.0.zip
* Extract it to a separate directory
* Load manifest.json from that separate directory using about:debugging
* Try whether the issue still occurs

**Comment by Nono-m0le** [comment]
Thanks, honestly I'll wait the new release as the workaround (black list) works really well for me for the time being. You know how sysadmin can be lazy sometimes

----- Message de réponse -----
De : "Geoffrey De Belie" <notifications@github.com>
Pour : "Smile4ever/firefoxaddons" <firefoxaddons@noreply.github.com>
Cc : "Nono" <nono@m0le.net>, "Author" <author@noreply.github.com>
Objet : [Smile4ever/firefoxaddons] Neat URL - Uanble to change user on Rainloop webmail (#79)
Date : ven., déc. 1, 2017 17:11

If I look at the logging, this might be fixed already with Neat URL 4.0.0 which will soon be released. You can test whether it solves your issue:

Download this ZIP file: https://github.com/Smile4ever/firefoxaddons/blob/master/Neat%20URL-webext/web-ext-artifacts/neat_url-4.0.0.zip
Extract it to a separate directory
Load manifest.json from that separate directory using about:debugging
Try whether the issue still occurs


&mdash;You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Smile4ever** [comment]
Please retest this using Neat URL 4.0.0 which is now available on addons.mozilla.org.

**Comment by Nono-m0le** [comment]
it works, thanks !
