### ISSUE TITLE
[Neat URL] removing params @ addons.mozilla

### ISSUE THREAD

**Issue by atomGit** [Smile4ever/firefoxaddons#80]
trying to remove params from AMO URLs...
`https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/?src=cb-dl-users`

so i added this to the list...
`src@addons.mozilla.org`

it works in the end, but the page loads twice, first with the params, then without

req. types is: `main_frame,beacon,ping,sub_frame,script,other`

this prompts the question as to **when** Neat URL is doing it's thing - is it cleaning URLs before any request to the site is made, or after?

**Comment by gwarser** [comment]
Heh :D again? https://github.com/Smile4ever/firefoxaddons/issues/48

**Comment by atomGit** [comment]
i read through #48 and i don't see how that plays in regarding this issue - you stated that Neat URL works on addons.mozilla, which it does, but the issue is why does the example page load twice? - once with the original URL and then immediately after with the cleaned URL

what i'm expecting to happen is that params (`?src=cb-dl-users`) are stripped before the request is ever sent, in which case the only thing the server would see is the URL without the params

**Comment by gwarser** [comment]
This is special case. Links to addons.mozilla.org cannot be cleaned. Workaround is to reload page. https://github.com/Smile4ever/firefoxaddons/issues/42#issuecomment-332473195

**Comment by atomGit** [comment]
thanks
