### ISSUE TITLE
Translate Now misfires when translating firefox addon descriptive page

### ISSUE THREAD

**Issue by griswolf** [Smile4ever/firefoxaddons#85]
This page https://addons.mozilla.org/en-US/firefox/addon/browser-security-1/
 (Browser-Security by Vondos Media GmbH: Browser Security - DER Schutz vor Phishing und Malware)

visit the page. Click the translate-now icon. Notice that it attempts to do something, then quickly (perhaps immediately? Cache??) shows first image.
<img width="1279" alt="ss 2017-11-14 at 23 52 44" src="https://user-images.githubusercontent.com/3092067/32824735-fa2708b4-c996-11e7-9895-5e19cd45e1ea.png">
OK. Lets try right-clicking on a page with nothing selected. Effectively identical.
It _does_ work to select and right click, which I failed to find on the first attempt (what can I say? I tend to read about 75% of what passes before my eyes).

**Comment by Smile4ever** [comment]
Please note that this is related to the new design of addons.mozilla.org. There is nothing I can do here; it is beyond my control. Google Translate does not seem to support addons.mozilla.org with the new design and Mozilla didn't take this into account. I will file a bug at Mozilla.

**Comment by Smile4ever** [comment]
Please follow the referenced bug, I will now close this one.
