### ISSUE TITLE
[Translate Now] Does not work anymore with Deepl

### ISSUE THREAD

**Issue by EtienneM** [Smile4ever/firefoxaddons#87]
When I click on "Translate with DeepL" I land on this [page](https://www.deepl.com/translator) without any text in any text boxes

**Comment by Smile4ever** [comment]
Will investigate.

**Comment by Smile4ever** [comment]
They changed from using IDs to classes. I changed Translate Now accordingly. It's available in Translate Now 3.1.4 which is available on addons.mozilla.org.

**Comment by EtienneM** [comment]
Wow that was a quick fix, thanks a lot!
