### ISSUE TITLE
“Get Archive” to webextension

### ISSUE THREAD

**Issue by yfdyh000** [Smile4ever/firefoxaddons#9]
i.e. https://addons.mozilla.org/firefox/addon/get-archive/. like https://addons.mozilla.org/firefox/addon/archive-webextension/

**Comment by Smile4ever** [comment]
Im currently working on a SDK extension with jpm because not every API I need is available with WebExtensions, but I will take a look.

**Comment by Smile4ever** [comment]
I have a WebExtension version working. I will release it when I have applied the finishing touches to it.

**Comment by Smile4ever** [comment]
I've submitted the WebExtension version to AMO.

**Comment by Smile4ever** [comment]
It has been available on AMO for at least a few days now. Feel free to open issues about the new WebExtension version.
