### ISSUE TITLE
Translate Now - addon toolbar button iframe/frame selections don't work

### ISSUE THREAD

**Issue by drmusti** [Smile4ever/firefoxaddons#90]
hi dear author
your addon toolbar button iframe texts and frame text false. dont work. :(
please find solution.
thanks.

**Comment by Smile4ever** [comment]
On which site do you experience this issue?

**Comment by drmusti** [comment]
FF v57  all iframe , frames. all sites if iframe.

**Comment by Smile4ever** [comment]
The iframe handling was indeed not working anymore, will be fixed in the next release. That solves the w3schools selection.

On opec.org: iframe is HTTPS, page is HTTP. Unfortunately that does not work due to technical limitations so there is nothing that can be done here.

**Comment by Smile4ever** [comment]
This has been fixed in Translate Now 3.1.5.

**Comment by drmusti** [comment]
please exaple a url for this solution for test.
thanks

**Comment by Smile4ever** [comment]
You can use https://www.w3schools.com/html/html_iframe.asp
Select any text in the iframe and click on the toolbar button.

For the remaining cases that don't work, I'm afraid nothing can be done except for teaching users to use the context menus.

**Comment by drmusti** [comment]
yes working in frame  button action . you great coder. super programmer. bravo.

**Comment by drmusti** [comment]
http://urlmidi.com/test
dear dont work some iframes. examle urlmidi 
http://urlmidi.com/test
please check.
Sincerely.

**Comment by Smile4ever** [comment]
This is due to mixed HTTP / HTTPS usage.
