### ISSUE TITLE
Neaturl: "Show counter" setting doesn't do anything

### ISSUE THREAD

**Issue by d0mf1g** [Smile4ever/firefoxaddons#91]
Unchecking it still shows counters.

**Comment by Smile4ever** [comment]
I will investigate. Which Firefox version did you use and which version of Neat URL?

**Comment by d0mf1g** [comment]
Firefox 57

NeatURL 3.2.0

**Comment by Smile4ever** [comment]
Fixed in Neat URL 4.0.0 which is now available on addons.mozilla.org.
