### ISSUE TITLE
[Neat URL] Changing setting "URL request types" does not apply until FF restart

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#92]
Add `xmlhttprequest` to `URL request types`.
Restart FF.
Go to [Sample URL](http://www.24ur.com/novice/slovenija/znova-nas-bo-pobelil-sneg-najvec-ga-bo-na-gorenjskem-in-koroskem.html) where is a video, which doesn't work (does not even show).
Remove `xmlhttprequest` from `URL request types`.
Retry sample URL... it still does not work.
Restart FF.
Retry again and it works.

**Comment by Smile4ever** [comment]
Should be fixed in Neat URL 4.0.0, let me know if it isn't.
