### ISSUE TITLE
[Neat URL] Samples of strange changes where there should not be any

### ISSUE THREAD

**Issue by crssi** [Smile4ever/firefoxaddons#93]
`"Neat URL (type script): https://duckduckgo.com/t.js?q=the%20creation+of+the+nano+server+image+failed+the+request+is+not+supported+error+50&l=us-en&p=1&s=0&dl=en&ct=SI&ss_mkt=us&yhs=1 has been changed to https://duckduckgo.com/t.js?q=the+creation+of+the+nano+server+image+failed+the+request+is+not+supported+error+50&l=us-en&p=1&s=0&dl=en&ct=SI&ss_mkt=us&yhs=1"`

`"Neat URL (type stylesheet): https://fonts.googleapis.com/css?family=Open+Sans:400,400Italic,600,700|Roboto+Slab|Merriweather:300italic&subset has been changed to https://fonts.googleapis.com/css?family=Open+Sans:400,400Italic,600,700%7CRoboto+Slab%7CMerriweather:300italic&subset="`

I will collect samples in the next days when I will stumble on and will post them here?
The problem of those "changes" is also when in research mode it is a lot of false positives where digesting over them is time consuming. :(

**Comment by Smile4ever** [comment]
Do you have this with the version in git as well? I would like to release the git version soon which fixes a lot of these problems.

**Comment by crssi** [comment]
Doh... haven't tried with git version.
Where can I find compiled one on your git?

**Comment by Smile4ever** [comment]
There is none, but you can clone the source code repository (it's not that big) and load Neat URL-webext using about:debugging.

**Comment by crssi** [comment]
Oh... I see :)
When do you plan to release the latest on AMO?

Cheers

**Comment by Smile4ever** [comment]
I hope to do it soon, but I need to fix a bug first. I can't give you a deadline.

**Comment by Smile4ever** [comment]
@crssi I managed to fix a few outstanding bugs, I would like you to be my tester when I push the code to GitHub.

**Comment by crssi** [comment]
Sure. Let me know when you push to git and also give me a hint to what should I take special attention.

**Comment by Smile4ever** [comment]
Thanks. Testing time for Neat URL 4.0.0! See #94

**Comment by Smile4ever** [comment]
Fixed in Neat URL 4.0.0.
