### ISSUE TITLE
Neat URL - Dropdown menu in settings not displaying in correct position

### ISSUE THREAD

**Issue by d0mf1g** [Smile4ever/firefoxaddons#98]
The dropdown menu appears all the way at the bottom.

Neaturl 4
Firefox 57

**Comment by d0mf1g** [comment]
![image](https://user-images.githubusercontent.com/33993948/33785947-38b11dda-dc35-11e7-8f48-69e762f7a787.png)

**Comment by Smile4ever** [comment]
Do you have the same with N eat URL 3.2.0? Which operating system are you using?

**Comment by d0mf1g** [comment]
I am experiencing the same issue on both Windows 7 and 10. 

This issue occurred in version 3.2.0 as well if I remember correctly.

**Comment by crssi** [comment]
Same here, just a cosmetics.

To recreate a problem:
Go to NeatURL settings page, click on, for example, "Icon animation"... everything is OK.
Scroll page down a bit and do the previous line ^^ again. Now its NOT OK.

Cheers

**Comment by Smile4ever** [comment]
Sorry, I cannot reproduce on either Linux or Windows 10.
@d0mf1g Are you able to make a GIF or video demonstrating the problem and attach it here?

**Comment by Smile4ever** [comment]
Feel free to reopen when you have more information.
